2024-11-04 15:04:20,849 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [3750] [MainThread] - DEBUG - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=None, shell=False, universal_newlines=False)
2024-11-04 15:04:20,863 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [3750] [MainThread] - DEBUG - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=None, shell=False, universal_newlines=False)
2024-11-04 15:04:21,304 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [3750] [Thread-1 (wrapped_target)] - DEBUG - Starting new HTTPS connection (1): api.wandb.ai:443
2024-11-04 15:04:21,505 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [3750] [Thread-1 (wrapped_target)] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 1985
2024-11-04 15:04:21,667 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [3750] [Thread-1 (wrapped_target)] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 393
2024-11-04 15:04:21,704 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [3750] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-04 15:04:26,566 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:304] [3750] [MainThread] - DEBUG - Model name detected: old_money
2024-11-04 15:04:26,566 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [3750] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-04 15:04:26,566 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [3750] [MainThread] - DEBUG - Get key: 4ad6bf2c63a95f201e91d6cf2150ba18bffab26a12b4329015770e8cde65fa60 returned value: None
2024-11-04 15:04:26,566 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:258] [3750] [MainThread] - DEBUG - ModelPath instance 2 initialized for old_money.
2024-11-04 15:04:26,566 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [3750] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-04 15:04:26,567 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [3750] [MainThread] - DEBUG - Get key: 4ad6bf2c63a95f201e91d6cf2150ba18bffab26a12b4329015770e8cde65fa60 returned value: None
2024-11-04 15:04:26,567 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:340] [3750] [MainThread] - INFO - Writing <built-in method title of str object at 0x1072dea30>Path object to cache for model old_money.
2024-11-04 15:04:26,567 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:170] [3750] [MainThread] - DEBUG - Cache saved to file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-04 15:04:26,567 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:133] [3750] [MainThread] - DEBUG - Set key: 4ad6bf2c63a95f201e91d6cf2150ba18bffab26a12b4329015770e8cde65fa60 with value: <model_path.ModelPath object at 0x33a425f90>
2024-11-04 15:04:26,567 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:243] [3750] [MainThread] - INFO - Fetching data...
2024-11-04 15:04:26,567 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:37] [3750] [MainThread] - INFO - Beginning file download through viewser with month range 121,445
2024-11-04 15:04:26,567 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:304] [3750] [MainThread] - DEBUG - Model name detected: old_money
2024-11-04 15:04:26,567 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [3750] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-04 15:04:26,567 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [3750] [MainThread] - DEBUG - Get key: 4797fd2a078ba19f971319fcaa0c63a3070d79c86cc88e7fa72e2f953db1d27f returned value: <model_path.ModelPath object at 0x33a8a0f10>
2024-11-04 15:04:26,567 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:322] [3750] [MainThread] - INFO - ModelPath instance old_money found in GlobalCache. Using cached instance.
2024-11-04 15:04:26,567 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3750] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/artifacts does not exist. Continuing...
2024-11-04 15:04:26,567 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3750] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/data/generated does not exist. Continuing...
2024-11-04 15:04:26,568 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3750] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/data/processed does not exist. Continuing...
2024-11-04 15:04:26,568 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3750] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/architectures does not exist. Continuing...
2024-11-04 15:04:26,568 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3750] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/reports does not exist. Continuing...
2024-11-04 15:04:26,568 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3750] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/visualization does not exist. Continuing...
2024-11-04 15:04:26,568 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3750] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/architectures does not exist. Continuing...
2024-11-04 15:04:26,568 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3750] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/online_evaluation does not exist. Continuing...
2024-11-04 15:04:26,568 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3750] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/architectures does not exist. Continuing...
2024-11-04 15:04:26,568 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3750] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/online_evaluation does not exist. Continuing...
2024-11-04 15:04:26,568 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:258] [3750] [MainThread] - DEBUG - ModelPath instance 3 initialized for old_money.
2024-11-04 15:04:26,568 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [3750] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-04 15:04:26,568 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [3750] [MainThread] - DEBUG - Get key: 4797fd2a078ba19f971319fcaa0c63a3070d79c86cc88e7fa72e2f953db1d27f returned value: <model_path.ModelPath object at 0x33a811b50>
2024-11-04 15:04:26,570 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:484] [3750] [MainThread] - INFO - Queryset /Users/dylanpinheiro/Desktop/views_pipeline/common_querysets/queryset_old_money.py imported successfully.
2024-11-04 15:04:26,574 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:45] [3750] [MainThread] - INFO - Found queryset for old_money in common_querysets
2024-11-04 15:04:26,575 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:208] [3750] [MainThread] - INFO - Publishing queryset fatalities002_pgm_escwa_drought
2024-11-04 15:04:26,576 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [3750] [MainThread] - DEBUG - Starting new HTTPS connection (1): viewser.viewsforecasting.org:443
2024-11-04 15:04:27,172 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [3750] [MainThread] - DEBUG - https://viewser.viewsforecasting.org:443 "POST /querysets/querysets?overwrite=True HTTP/11" 200 None
2024-11-04 15:04:27,174 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:238] [3750] [MainThread] - INFO - Fetching queryset fatalities002_pgm_escwa_drought
2024-11-04 15:04:27,180 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [3750] [MainThread] - DEBUG - Starting new HTTPS connection (1): viewser.viewsforecasting.org:443
2024-11-04 15:04:50,212 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [3750] [MainThread] - DEBUG - https://viewser.viewsforecasting.org:443 "GET /querysets/data/fatalities002_pgm_escwa_drought?start_date=121&end_date=444 HTTP/11" 200 185580588
2024-11-04 15:05:13,212 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:377] [3750] [MainThread] - WARNING - DataFrame contains non-np.float64 numeric columns. Converting the following columns: greq_1_excluded
2024-11-04 15:05:13,217 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:56] [3750] [MainThread] - WARNING - {'old_money data alert 1': ' alarm: feature zero; offender: tlag1_dr_sev_gs, threshold: 0.95 Severity: 2 Timestamp: 2024-11-04 15:05:13\n, '}
2024-11-04 15:05:13,217 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:56] [3750] [MainThread] - WARNING - {'old_money data alert 2': ' alarm: feature zero; offender: ln_ged_sb_dep, threshold: 0.95 Severity: 2 Timestamp: 2024-11-04 15:05:13\n, '}
2024-11-04 15:05:13,217 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:56] [3750] [MainThread] - WARNING - {'old_money data alert 3': ' alarm: feature zero; offender: ln_ged_sb, threshold: 0.95 Severity: 2 Timestamp: 2024-11-04 15:05:13\n'}
2024-11-04 15:05:13,218 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_log_files.py [utils_log_files.py:57] [3750] [MainThread] - INFO - Data fetch log file created at /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/data/raw/calibration_data_fetch_log.txt
2024-11-04 15:05:13,218 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:250] [3750] [MainThread] - INFO - Saving data to /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/data/raw/calibration_viewser_df.pkl
2024-11-04 15:05:13,358 /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/dataloaders/get_data.py [get_data.py:12] [3750] [MainThread] - DEBUG - DataFrame shape: (4247640, 29)
2024-11-04 15:05:21,478 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [3750] [sentry-sdk.BackgroundWorker] - DEBUG - Starting new HTTPS connection (1): o151352.ingest.sentry.io:443
2024-11-04 15:05:21,576 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [3750] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-04 15:05:21,602 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [3750] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-04 15:05:27,227 /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/management/execute_model_tasks.py [execute_model_tasks.py:57] [3750] [MainThread] - INFO - Training model old_money...
2024-11-04 15:05:27,228 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:304] [3750] [MainThread] - DEBUG - Model name detected: old_money
2024-11-04 15:05:27,228 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [3750] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-04 15:05:27,228 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [3750] [MainThread] - DEBUG - Get key: 4797fd2a078ba19f971319fcaa0c63a3070d79c86cc88e7fa72e2f953db1d27f returned value: <model_path.ModelPath object at 0x33a63ffd0>
2024-11-04 15:05:27,228 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:322] [3750] [MainThread] - INFO - ModelPath instance old_money found in GlobalCache. Using cached instance.
2024-11-04 15:05:27,228 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3750] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/artifacts does not exist. Continuing...
2024-11-04 15:05:27,228 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3750] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/data/generated does not exist. Continuing...
2024-11-04 15:05:27,228 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3750] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/data/processed does not exist. Continuing...
2024-11-04 15:05:27,228 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3750] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/architectures does not exist. Continuing...
2024-11-04 15:05:27,228 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3750] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/reports does not exist. Continuing...
2024-11-04 15:05:27,229 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3750] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/visualization does not exist. Continuing...
2024-11-04 15:05:27,229 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3750] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/architectures does not exist. Continuing...
2024-11-04 15:05:27,229 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3750] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/online_evaluation does not exist. Continuing...
2024-11-04 15:05:27,229 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3750] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/architectures does not exist. Continuing...
2024-11-04 15:05:27,229 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3750] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/online_evaluation does not exist. Continuing...
2024-11-04 15:05:27,229 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:258] [3750] [MainThread] - DEBUG - ModelPath instance 4 initialized for old_money.
2024-11-04 15:05:27,229 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [3750] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-04 15:05:27,229 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [3750] [MainThread] - DEBUG - Get key: 4797fd2a078ba19f971319fcaa0c63a3070d79c86cc88e7fa72e2f953db1d27f returned value: <model_path.ModelPath object at 0x33a588bd0>
2024-11-04 15:05:37,001 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [3750] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-04 15:05:39,044 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [3750] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
2024-11-04 15:06:14,889 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [3926] [MainThread] - DEBUG - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=None, shell=False, universal_newlines=False)
2024-11-04 15:06:14,901 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [3926] [MainThread] - DEBUG - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=None, shell=False, universal_newlines=False)
2024-11-04 15:06:15,336 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [3926] [Thread-1 (wrapped_target)] - DEBUG - Starting new HTTPS connection (1): api.wandb.ai:443
2024-11-04 15:06:15,522 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [3926] [Thread-1 (wrapped_target)] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 1985
2024-11-04 15:06:15,675 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [3926] [Thread-1 (wrapped_target)] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 393
2024-11-04 15:06:15,714 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [3926] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-04 15:06:20,430 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:304] [3926] [MainThread] - DEBUG - Model name detected: old_money
2024-11-04 15:06:20,431 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [3926] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-04 15:06:20,431 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [3926] [MainThread] - DEBUG - Get key: 4ad6bf2c63a95f201e91d6cf2150ba18bffab26a12b4329015770e8cde65fa60 returned value: None
2024-11-04 15:06:20,431 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:258] [3926] [MainThread] - DEBUG - ModelPath instance 2 initialized for old_money.
2024-11-04 15:06:20,431 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [3926] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-04 15:06:20,431 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [3926] [MainThread] - DEBUG - Get key: 4ad6bf2c63a95f201e91d6cf2150ba18bffab26a12b4329015770e8cde65fa60 returned value: None
2024-11-04 15:06:20,431 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:340] [3926] [MainThread] - INFO - Writing <built-in method title of str object at 0x10622eb30>Path object to cache for model old_money.
2024-11-04 15:06:20,431 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:170] [3926] [MainThread] - DEBUG - Cache saved to file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-04 15:06:20,431 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:133] [3926] [MainThread] - DEBUG - Set key: 4ad6bf2c63a95f201e91d6cf2150ba18bffab26a12b4329015770e8cde65fa60 with value: <model_path.ModelPath object at 0x30afb3010>
2024-11-04 15:06:20,431 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:243] [3926] [MainThread] - INFO - Fetching data...
2024-11-04 15:06:20,431 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:37] [3926] [MainThread] - INFO - Beginning file download through viewser with month range 121,445
2024-11-04 15:06:20,431 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:304] [3926] [MainThread] - DEBUG - Model name detected: old_money
2024-11-04 15:06:20,432 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [3926] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-04 15:06:20,432 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [3926] [MainThread] - DEBUG - Get key: 4797fd2a078ba19f971319fcaa0c63a3070d79c86cc88e7fa72e2f953db1d27f returned value: <model_path.ModelPath object at 0x30b323810>
2024-11-04 15:06:20,432 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:322] [3926] [MainThread] - INFO - ModelPath instance old_money found in GlobalCache. Using cached instance.
2024-11-04 15:06:20,432 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3926] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/artifacts does not exist. Continuing...
2024-11-04 15:06:20,432 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3926] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/data/generated does not exist. Continuing...
2024-11-04 15:06:20,432 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3926] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/data/processed does not exist. Continuing...
2024-11-04 15:06:20,432 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3926] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/architectures does not exist. Continuing...
2024-11-04 15:06:20,432 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3926] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/reports does not exist. Continuing...
2024-11-04 15:06:20,432 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3926] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/visualization does not exist. Continuing...
2024-11-04 15:06:20,432 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3926] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/architectures does not exist. Continuing...
2024-11-04 15:06:20,432 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3926] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/online_evaluation does not exist. Continuing...
2024-11-04 15:06:20,432 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3926] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/architectures does not exist. Continuing...
2024-11-04 15:06:20,433 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3926] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/online_evaluation does not exist. Continuing...
2024-11-04 15:06:20,433 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:258] [3926] [MainThread] - DEBUG - ModelPath instance 3 initialized for old_money.
2024-11-04 15:06:20,433 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [3926] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-04 15:06:20,433 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [3926] [MainThread] - DEBUG - Get key: 4797fd2a078ba19f971319fcaa0c63a3070d79c86cc88e7fa72e2f953db1d27f returned value: <model_path.ModelPath object at 0x30b3a6e50>
2024-11-04 15:06:20,433 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:484] [3926] [MainThread] - INFO - Queryset /Users/dylanpinheiro/Desktop/views_pipeline/common_querysets/queryset_old_money.py imported successfully.
2024-11-04 15:06:20,438 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:45] [3926] [MainThread] - INFO - Found queryset for old_money in common_querysets
2024-11-04 15:06:20,438 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:208] [3926] [MainThread] - INFO - Publishing queryset fatalities002_pgm_escwa_drought
2024-11-04 15:06:20,439 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [3926] [MainThread] - DEBUG - Starting new HTTPS connection (1): viewser.viewsforecasting.org:443
2024-11-04 15:06:21,042 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [3926] [MainThread] - DEBUG - https://viewser.viewsforecasting.org:443 "POST /querysets/querysets?overwrite=True HTTP/11" 200 None
2024-11-04 15:06:21,043 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:238] [3926] [MainThread] - INFO - Fetching queryset fatalities002_pgm_escwa_drought
2024-11-04 15:06:21,047 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [3926] [MainThread] - DEBUG - Starting new HTTPS connection (1): viewser.viewsforecasting.org:443
2024-11-04 15:06:42,637 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [3926] [MainThread] - DEBUG - https://viewser.viewsforecasting.org:443 "GET /querysets/data/fatalities002_pgm_escwa_drought?start_date=121&end_date=444 HTTP/11" 200 185580588
2024-11-04 15:07:04,382 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:377] [3926] [MainThread] - WARNING - DataFrame contains non-np.float64 numeric columns. Converting the following columns: greq_1_excluded
2024-11-04 15:07:04,386 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:56] [3926] [MainThread] - WARNING - {'old_money data alert 1': ' alarm: feature zero; offender: tlag1_dr_sev_gs, threshold: 0.95 Severity: 2 Timestamp: 2024-11-04 15:07:04\n, '}
2024-11-04 15:07:04,387 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:56] [3926] [MainThread] - WARNING - {'old_money data alert 2': ' alarm: feature zero; offender: ln_ged_sb_dep, threshold: 0.95 Severity: 2 Timestamp: 2024-11-04 15:07:04\n, '}
2024-11-04 15:07:04,387 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:56] [3926] [MainThread] - WARNING - {'old_money data alert 3': ' alarm: feature zero; offender: ln_ged_sb, threshold: 0.95 Severity: 2 Timestamp: 2024-11-04 15:07:04\n'}
2024-11-04 15:07:04,387 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_log_files.py [utils_log_files.py:57] [3926] [MainThread] - INFO - Data fetch log file created at /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/data/raw/calibration_data_fetch_log.txt
2024-11-04 15:07:04,387 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:250] [3926] [MainThread] - INFO - Saving data to /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/data/raw/calibration_viewser_df.pkl
2024-11-04 15:07:04,539 /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/dataloaders/get_data.py [get_data.py:12] [3926] [MainThread] - DEBUG - DataFrame shape: (4247640, 29)
2024-11-04 15:07:12,303 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [3926] [sentry-sdk.BackgroundWorker] - DEBUG - Starting new HTTPS connection (1): o151352.ingest.sentry.io:443
2024-11-04 15:07:12,387 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [3926] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-04 15:07:12,412 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [3926] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-04 15:07:18,036 /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/management/execute_model_tasks.py [execute_model_tasks.py:57] [3926] [MainThread] - INFO - Training model old_money...
2024-11-04 15:07:18,037 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:304] [3926] [MainThread] - DEBUG - Model name detected: old_money
2024-11-04 15:07:18,037 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [3926] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-04 15:07:18,037 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [3926] [MainThread] - DEBUG - Get key: 4797fd2a078ba19f971319fcaa0c63a3070d79c86cc88e7fa72e2f953db1d27f returned value: <model_path.ModelPath object at 0x30af5ac50>
2024-11-04 15:07:18,037 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:322] [3926] [MainThread] - INFO - ModelPath instance old_money found in GlobalCache. Using cached instance.
2024-11-04 15:07:18,037 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3926] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/artifacts does not exist. Continuing...
2024-11-04 15:07:18,037 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3926] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/data/generated does not exist. Continuing...
2024-11-04 15:07:18,037 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3926] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/data/processed does not exist. Continuing...
2024-11-04 15:07:18,037 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3926] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/architectures does not exist. Continuing...
2024-11-04 15:07:18,037 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3926] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/reports does not exist. Continuing...
2024-11-04 15:07:18,038 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3926] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/visualization does not exist. Continuing...
2024-11-04 15:07:18,038 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3926] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/architectures does not exist. Continuing...
2024-11-04 15:07:18,038 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3926] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/online_evaluation does not exist. Continuing...
2024-11-04 15:07:18,038 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3926] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/architectures does not exist. Continuing...
2024-11-04 15:07:18,038 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [3926] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/online_evaluation does not exist. Continuing...
2024-11-04 15:07:18,038 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:258] [3926] [MainThread] - DEBUG - ModelPath instance 4 initialized for old_money.
2024-11-04 15:07:18,038 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [3926] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-04 15:07:18,038 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [3926] [MainThread] - DEBUG - Get key: 4797fd2a078ba19f971319fcaa0c63a3070d79c86cc88e7fa72e2f953db1d27f returned value: <model_path.ModelPath object at 0x30b030510>
2024-11-04 15:07:26,494 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [3926] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-04 15:07:28,524 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [3926] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
2024-11-04 15:14:20,720 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [4277] [MainThread] - DEBUG - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=None, shell=False, universal_newlines=False)
2024-11-04 15:14:20,733 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [4277] [MainThread] - DEBUG - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=None, shell=False, universal_newlines=False)
2024-11-04 15:14:21,177 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [4277] [Thread-1 (wrapped_target)] - DEBUG - Starting new HTTPS connection (1): api.wandb.ai:443
2024-11-04 15:14:21,365 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [4277] [Thread-1 (wrapped_target)] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 1985
2024-11-04 15:14:21,520 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [4277] [Thread-1 (wrapped_target)] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 393
2024-11-04 15:14:21,542 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [4277] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-04 15:14:26,296 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:304] [4277] [MainThread] - DEBUG - Model name detected: old_money
2024-11-04 15:14:26,296 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [4277] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-04 15:14:26,296 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [4277] [MainThread] - DEBUG - Get key: 4ad6bf2c63a95f201e91d6cf2150ba18bffab26a12b4329015770e8cde65fa60 returned value: None
2024-11-04 15:14:26,296 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:258] [4277] [MainThread] - DEBUG - ModelPath instance 2 initialized for old_money.
2024-11-04 15:14:26,296 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [4277] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-04 15:14:26,296 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [4277] [MainThread] - DEBUG - Get key: 4ad6bf2c63a95f201e91d6cf2150ba18bffab26a12b4329015770e8cde65fa60 returned value: None
2024-11-04 15:14:26,296 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:340] [4277] [MainThread] - INFO - Writing <built-in method title of str object at 0x1029aab30>Path object to cache for model old_money.
2024-11-04 15:14:26,296 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:170] [4277] [MainThread] - DEBUG - Cache saved to file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-04 15:14:26,296 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:133] [4277] [MainThread] - DEBUG - Set key: 4ad6bf2c63a95f201e91d6cf2150ba18bffab26a12b4329015770e8cde65fa60 with value: <model_path.ModelPath object at 0x30d507110>
2024-11-04 15:14:26,296 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:243] [4277] [MainThread] - INFO - Fetching data...
2024-11-04 15:14:26,297 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:37] [4277] [MainThread] - INFO - Beginning file download through viewser with month range 121,445
2024-11-04 15:14:26,297 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:304] [4277] [MainThread] - DEBUG - Model name detected: old_money
2024-11-04 15:14:26,297 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [4277] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-04 15:14:26,297 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [4277] [MainThread] - DEBUG - Get key: 4797fd2a078ba19f971319fcaa0c63a3070d79c86cc88e7fa72e2f953db1d27f returned value: <model_path.ModelPath object at 0x30d876a10>
2024-11-04 15:14:26,297 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:322] [4277] [MainThread] - INFO - ModelPath instance old_money found in GlobalCache. Using cached instance.
2024-11-04 15:14:26,297 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [4277] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/artifacts does not exist. Continuing...
2024-11-04 15:14:26,297 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [4277] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/data/generated does not exist. Continuing...
2024-11-04 15:14:26,297 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [4277] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/data/processed does not exist. Continuing...
2024-11-04 15:14:26,297 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [4277] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/architectures does not exist. Continuing...
2024-11-04 15:14:26,297 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [4277] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/reports does not exist. Continuing...
2024-11-04 15:14:26,297 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [4277] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/visualization does not exist. Continuing...
2024-11-04 15:14:26,297 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [4277] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/architectures does not exist. Continuing...
2024-11-04 15:14:26,298 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [4277] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/online_evaluation does not exist. Continuing...
2024-11-04 15:14:26,298 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [4277] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/architectures does not exist. Continuing...
2024-11-04 15:14:26,298 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [4277] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/online_evaluation does not exist. Continuing...
2024-11-04 15:14:26,298 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:258] [4277] [MainThread] - DEBUG - ModelPath instance 3 initialized for old_money.
2024-11-04 15:14:26,298 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [4277] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-04 15:14:26,298 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [4277] [MainThread] - DEBUG - Get key: 4797fd2a078ba19f971319fcaa0c63a3070d79c86cc88e7fa72e2f953db1d27f returned value: <model_path.ModelPath object at 0x30d5f0ed0>
2024-11-04 15:14:26,298 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:484] [4277] [MainThread] - INFO - Queryset /Users/dylanpinheiro/Desktop/views_pipeline/common_querysets/queryset_old_money.py imported successfully.
2024-11-04 15:14:26,303 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:45] [4277] [MainThread] - INFO - Found queryset for old_money in common_querysets
2024-11-04 15:14:26,303 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:208] [4277] [MainThread] - INFO - Publishing queryset fatalities002_pgm_escwa_drought
2024-11-04 15:14:26,305 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [4277] [MainThread] - DEBUG - Starting new HTTPS connection (1): viewser.viewsforecasting.org:443
2024-11-04 15:14:26,825 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [4277] [MainThread] - DEBUG - https://viewser.viewsforecasting.org:443 "POST /querysets/querysets?overwrite=True HTTP/11" 200 None
2024-11-04 15:14:26,826 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:238] [4277] [MainThread] - INFO - Fetching queryset fatalities002_pgm_escwa_drought
2024-11-04 15:14:26,830 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [4277] [MainThread] - DEBUG - Starting new HTTPS connection (1): viewser.viewsforecasting.org:443
2024-11-04 15:14:48,222 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [4277] [MainThread] - DEBUG - https://viewser.viewsforecasting.org:443 "GET /querysets/data/fatalities002_pgm_escwa_drought?start_date=121&end_date=444 HTTP/11" 200 185580588
2024-11-04 15:15:10,432 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:377] [4277] [MainThread] - WARNING - DataFrame contains non-np.float64 numeric columns. Converting the following columns: greq_1_excluded
2024-11-04 15:15:10,437 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:56] [4277] [MainThread] - WARNING - {'old_money data alert 1': ' alarm: feature zero; offender: tlag1_dr_sev_gs, threshold: 0.95 Severity: 2 Timestamp: 2024-11-04 15:15:10\n, '}
2024-11-04 15:15:10,437 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:56] [4277] [MainThread] - WARNING - {'old_money data alert 2': ' alarm: feature zero; offender: ln_ged_sb_dep, threshold: 0.95 Severity: 2 Timestamp: 2024-11-04 15:15:10\n, '}
2024-11-04 15:15:10,438 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:56] [4277] [MainThread] - WARNING - {'old_money data alert 3': ' alarm: feature zero; offender: ln_ged_sb, threshold: 0.95 Severity: 2 Timestamp: 2024-11-04 15:15:10\n'}
2024-11-04 15:15:10,439 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_log_files.py [utils_log_files.py:57] [4277] [MainThread] - INFO - Data fetch log file created at /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/data/raw/calibration_data_fetch_log.txt
2024-11-04 15:15:10,439 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:250] [4277] [MainThread] - INFO - Saving data to /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/data/raw/calibration_viewser_df.pkl
2024-11-04 15:15:10,595 /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/dataloaders/get_data.py [get_data.py:12] [4277] [MainThread] - DEBUG - DataFrame shape: (4247640, 29)
2024-11-04 15:15:17,196 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [4277] [sentry-sdk.BackgroundWorker] - DEBUG - Starting new HTTPS connection (1): o151352.ingest.sentry.io:443
2024-11-04 15:15:17,330 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [4277] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-04 15:15:17,355 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [4277] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-04 15:15:22,921 /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/management/execute_model_tasks.py [execute_model_tasks.py:57] [4277] [MainThread] - INFO - Training model old_money...
2024-11-04 15:15:22,921 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:304] [4277] [MainThread] - DEBUG - Model name detected: old_money
2024-11-04 15:15:22,921 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [4277] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-04 15:15:22,921 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [4277] [MainThread] - DEBUG - Get key: 4797fd2a078ba19f971319fcaa0c63a3070d79c86cc88e7fa72e2f953db1d27f returned value: <model_path.ModelPath object at 0x30d516510>
2024-11-04 15:15:22,921 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:322] [4277] [MainThread] - INFO - ModelPath instance old_money found in GlobalCache. Using cached instance.
2024-11-04 15:15:22,921 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [4277] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/artifacts does not exist. Continuing...
2024-11-04 15:15:22,921 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [4277] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/data/generated does not exist. Continuing...
2024-11-04 15:15:22,922 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [4277] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/data/processed does not exist. Continuing...
2024-11-04 15:15:22,922 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [4277] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/architectures does not exist. Continuing...
2024-11-04 15:15:22,922 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [4277] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/reports does not exist. Continuing...
2024-11-04 15:15:22,922 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [4277] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/visualization does not exist. Continuing...
2024-11-04 15:15:22,922 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [4277] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/architectures does not exist. Continuing...
2024-11-04 15:15:22,922 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [4277] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/online_evaluation does not exist. Continuing...
2024-11-04 15:15:22,922 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [4277] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/architectures does not exist. Continuing...
2024-11-04 15:15:22,922 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [4277] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/old_money/src/online_evaluation does not exist. Continuing...
2024-11-04 15:15:22,922 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:258] [4277] [MainThread] - DEBUG - ModelPath instance 4 initialized for old_money.
2024-11-04 15:15:22,923 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [4277] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-04 15:15:22,923 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [4277] [MainThread] - DEBUG - Get key: 4797fd2a078ba19f971319fcaa0c63a3070d79c86cc88e7fa72e2f953db1d27f returned value: <model_path.ModelPath object at 0x30d3f8e10>
2024-11-04 15:15:32,634 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [4277] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-04 15:15:34,691 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [4277] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
