2024-11-08 13:42:27,806 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [46804] [MainThread] - DEBUG - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=None, shell=False, universal_newlines=False)
2024-11-08 13:42:27,818 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [46804] [MainThread] - DEBUG - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=None, shell=False, universal_newlines=False)
2024-11-08 13:42:28,266 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [46804] [Thread-1 (wrapped_target)] - DEBUG - Starting new HTTPS connection (1): api.wandb.ai:443
2024-11-08 13:42:28,459 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [46804] [Thread-1 (wrapped_target)] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 1985
2024-11-08 13:42:28,621 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [46804] [Thread-1 (wrapped_target)] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 393
2024-11-08 13:42:28,625 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:308] [46804] [MainThread] - DEBUG - Path input detected: /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/main.py
2024-11-08 13:42:28,625 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:202] [46804] [MainThread] - INFO - Extracting model name from Path: /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/main.py
2024-11-08 13:42:28,626 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:207] [46804] [MainThread] - INFO - Valid model name orange_pasta found in path /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/main.py
2024-11-08 13:42:28,626 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:312] [46804] [MainThread] - DEBUG - Model name extracted from path: orange_pasta
2024-11-08 13:42:28,627 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [46804] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-08 13:42:28,627 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [46804] [MainThread] - DEBUG - Get key: 893440357c1a47ba97a9ce7646da5a99b1f2439e5a5320bfa57ea1770ca0968f returned value: <model_path.ModelPath object at 0x30b4b3390>
2024-11-08 13:42:28,627 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:343] [46804] [MainThread] - INFO - ModelPath instance orange_pasta found in GlobalCache. Using cached instance.
2024-11-08 13:42:28,628 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:279] [46804] [MainThread] - DEBUG - ModelPath instance 1 initialized for orange_pasta.
2024-11-08 13:42:28,628 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [46804] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-08 13:42:28,629 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [46804] [MainThread] - DEBUG - Get key: 893440357c1a47ba97a9ce7646da5a99b1f2439e5a5320bfa57ea1770ca0968f returned value: <model_path.ModelPath object at 0x30b82bc90>
2024-11-08 13:42:28,664 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [46804] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-08 13:42:33,418 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:283] [46804] [MainThread] - INFO - Fetching data from viewser...
2024-11-08 13:42:33,418 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:115] [46804] [MainThread] - INFO - Beginning file download through viewser with month range 121,445
2024-11-08 13:42:33,420 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:517] [46804] [MainThread] - INFO - Queryset /Users/dylanpinheiro/Desktop/views_pipeline/common_querysets/queryset_orange_pasta.py imported successfully.
2024-11-08 13:42:33,421 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:125] [46804] [MainThread] - INFO - Found queryset for orange_pasta in common_querysets
2024-11-08 13:42:33,421 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:208] [46804] [MainThread] - INFO - Publishing queryset fatalities003_pgm_baseline
2024-11-08 13:42:33,422 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [46804] [MainThread] - DEBUG - Starting new HTTPS connection (1): viewser.viewsforecasting.org:443
2024-11-08 13:42:33,673 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [46804] [MainThread] - DEBUG - https://viewser.viewsforecasting.org:443 "POST /querysets/querysets?overwrite=True HTTP/11" 200 None
2024-11-08 13:42:33,675 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:238] [46804] [MainThread] - INFO - Fetching queryset fatalities003_pgm_baseline
2024-11-08 13:42:33,680 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [46804] [MainThread] - DEBUG - Starting new HTTPS connection (1): viewser.viewsforecasting.org:443
2024-11-08 13:42:42,897 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [46804] [MainThread] - DEBUG - https://viewser.viewsforecasting.org:443 "GET /querysets/data/fatalities003_pgm_baseline?start_date=121&end_date=444 HTTP/11" 200 37032565
2024-11-08 13:42:52,495 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:140] [46804] [MainThread] - WARNING - {'orange_pasta data alert 1': ' alarm: feature zero; offender: ged_sb_dep, threshold: 0.95 Severity: 2 Timestamp: 2024-11-08 13:42:52\n, '}
2024-11-08 13:42:52,495 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:140] [46804] [MainThread] - WARNING - {'orange_pasta data alert 2': ' alarm: feature zero; offender: ln_ged_sb, threshold: 0.95 Severity: 2 Timestamp: 2024-11-08 13:42:52\n'}
2024-11-08 13:42:52,495 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_log_files.py [utils_log_files.py:57] [46804] [MainThread] - INFO - Data fetch log file created at /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/data/raw/calibration_data_fetch_log.txt
2024-11-08 13:42:52,496 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:291] [46804] [MainThread] - INFO - Saving data to /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/data/raw/calibration_viewser_df.pkl
2024-11-08 13:43:00,254 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [46804] [sentry-sdk.BackgroundWorker] - DEBUG - Starting new HTTPS connection (1): o151352.ingest.sentry.io:443
2024-11-08 13:43:00,336 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [46804] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-08 13:43:00,359 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [46804] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-08 13:43:14,877 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [46804] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-08 13:43:14,904 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [46804] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-08 13:43:30,418 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [46804] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-08 13:43:32,472 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [46804] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
2024-11-08 14:02:51,706 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [47342] [MainThread] - DEBUG - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=None, shell=False, universal_newlines=False)
2024-11-08 14:02:51,719 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [47342] [MainThread] - DEBUG - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=None, shell=False, universal_newlines=False)
2024-11-08 14:02:52,165 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [47342] [Thread-1 (wrapped_target)] - DEBUG - Starting new HTTPS connection (1): api.wandb.ai:443
2024-11-08 14:02:52,370 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [47342] [Thread-1 (wrapped_target)] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 1985
2024-11-08 14:02:52,525 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [47342] [Thread-1 (wrapped_target)] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 393
2024-11-08 14:02:52,527 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:308] [47342] [MainThread] - DEBUG - Path input detected: /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/main.py
2024-11-08 14:02:52,527 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:202] [47342] [MainThread] - INFO - Extracting model name from Path: /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/main.py
2024-11-08 14:02:52,527 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:207] [47342] [MainThread] - INFO - Valid model name orange_pasta found in path /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/main.py
2024-11-08 14:02:52,527 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:312] [47342] [MainThread] - DEBUG - Model name extracted from path: orange_pasta
2024-11-08 14:02:52,528 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [47342] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-08 14:02:52,528 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [47342] [MainThread] - DEBUG - Get key: 893440357c1a47ba97a9ce7646da5a99b1f2439e5a5320bfa57ea1770ca0968f returned value: <model_path.ModelPath object at 0x310ac6f50>
2024-11-08 14:02:52,528 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:343] [47342] [MainThread] - INFO - ModelPath instance orange_pasta found in GlobalCache. Using cached instance.
2024-11-08 14:02:52,528 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:279] [47342] [MainThread] - DEBUG - ModelPath instance 1 initialized for orange_pasta.
2024-11-08 14:02:52,529 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [47342] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-08 14:02:52,529 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [47342] [MainThread] - DEBUG - Get key: 893440357c1a47ba97a9ce7646da5a99b1f2439e5a5320bfa57ea1770ca0968f returned value: <model_path.ModelPath object at 0x310a38990>
2024-11-08 14:02:52,551 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [47342] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-08 14:02:57,171 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:283] [47342] [MainThread] - INFO - Fetching data from viewser...
2024-11-08 14:02:57,171 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:115] [47342] [MainThread] - INFO - Beginning file download through viewser with month range 121,445
2024-11-08 14:02:57,171 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:517] [47342] [MainThread] - INFO - Queryset /Users/dylanpinheiro/Desktop/views_pipeline/common_querysets/queryset_orange_pasta.py imported successfully.
2024-11-08 14:02:57,172 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:125] [47342] [MainThread] - INFO - Found queryset for orange_pasta in common_querysets
2024-11-08 14:02:57,172 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:208] [47342] [MainThread] - INFO - Publishing queryset fatalities003_pgm_baseline
2024-11-08 14:02:57,174 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [47342] [MainThread] - DEBUG - Starting new HTTPS connection (1): viewser.viewsforecasting.org:443
2024-11-08 14:02:57,530 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [47342] [MainThread] - DEBUG - https://viewser.viewsforecasting.org:443 "POST /querysets/querysets?overwrite=True HTTP/11" 200 None
2024-11-08 14:02:57,531 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:238] [47342] [MainThread] - INFO - Fetching queryset fatalities003_pgm_baseline
2024-11-08 14:02:57,534 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [47342] [MainThread] - DEBUG - Starting new HTTPS connection (1): viewser.viewsforecasting.org:443
2024-11-08 14:03:06,996 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [47342] [MainThread] - DEBUG - https://viewser.viewsforecasting.org:443 "GET /querysets/data/fatalities003_pgm_baseline?start_date=121&end_date=444 HTTP/11" 200 37032565
2024-11-08 14:03:16,634 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:140] [47342] [MainThread] - WARNING - {'orange_pasta data alert 1': ' alarm: feature zero; offender: ged_sb_dep, threshold: 0.95 Severity: 2 Timestamp: 2024-11-08 14:03:16\n, '}
2024-11-08 14:03:16,635 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:140] [47342] [MainThread] - WARNING - {'orange_pasta data alert 2': ' alarm: feature zero; offender: ln_ged_sb, threshold: 0.95 Severity: 2 Timestamp: 2024-11-08 14:03:16\n'}
2024-11-08 14:03:16,635 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_log_files.py [utils_log_files.py:57] [47342] [MainThread] - INFO - Data fetch log file created at /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/data/raw/calibration_data_fetch_log.txt
2024-11-08 14:03:16,635 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:291] [47342] [MainThread] - INFO - Saving data to /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/data/raw/calibration_viewser_df.pkl
2024-11-08 14:03:22,060 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [47342] [sentry-sdk.BackgroundWorker] - DEBUG - Starting new HTTPS connection (1): o151352.ingest.sentry.io:443
2024-11-08 14:03:22,157 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [47342] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-08 14:03:22,183 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [47342] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-08 14:03:33,685 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [47342] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-08 14:03:33,710 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [47342] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-08 14:03:39,229 /Users/dylanpinheiro/Desktop/views_pipeline/model_manager.py [model_manager.py:331] [47342] [MainThread] - INFO - Training model orange_pasta...
2024-11-08 14:03:39,229 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:325] [47342] [MainThread] - DEBUG - Model name detected: orange_pasta
2024-11-08 14:03:39,229 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [47342] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-08 14:03:39,229 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [47342] [MainThread] - DEBUG - Get key: 893440357c1a47ba97a9ce7646da5a99b1f2439e5a5320bfa57ea1770ca0968f returned value: <model_path.ModelPath object at 0x31075d290>
2024-11-08 14:03:39,229 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:343] [47342] [MainThread] - INFO - ModelPath instance orange_pasta found in GlobalCache. Using cached instance.
2024-11-08 14:03:39,230 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:279] [47342] [MainThread] - DEBUG - ModelPath instance 2 initialized for orange_pasta.
2024-11-08 14:03:39,230 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [47342] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-08 14:03:39,230 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [47342] [MainThread] - DEBUG - Get key: 893440357c1a47ba97a9ce7646da5a99b1f2439e5a5320bfa57ea1770ca0968f returned value: <model_path.ModelPath object at 0x3107219d0>
2024-11-08 14:03:39,334 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/darts/timeseries.py [timeseries.py:821] [47342] [MainThread] - WARNING - UserWarning: `time_col` was not set and `df` has a monotonically increasing (time) index. This results in time series groups with non-overlapping (time) index. You can ignore this warning if the index represents the actual index of each individual time series group.
2024-11-08 14:05:33,392 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_log_files.py [utils_log_files.py:119] [47342] [MainThread] - INFO - Log file created at /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/data/generated/calibration_log.txt
2024-11-08 14:05:33,604 /Users/dylanpinheiro/Desktop/views_pipeline/model_manager.py [model_manager.py:336] [47342] [MainThread] - INFO - Done. Runtime: 1.906 minutes.

2024-11-08 14:05:42,288 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [47342] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-08 14:05:42,312 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [47342] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-08 14:05:56,797 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [47342] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-08 14:05:56,818 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [47342] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-08 14:06:11,956 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [47342] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-08 14:06:11,980 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [47342] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-08 14:06:23,448 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [47342] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-08 14:06:25,494 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [47342] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
2024-11-08 14:20:11,231 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [48005] [MainThread] - DEBUG - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=None, shell=False, universal_newlines=False)
2024-11-08 14:20:11,243 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [48005] [MainThread] - DEBUG - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=None, shell=False, universal_newlines=False)
2024-11-08 14:20:11,686 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [48005] [Thread-1 (wrapped_target)] - DEBUG - Starting new HTTPS connection (1): api.wandb.ai:443
2024-11-08 14:20:11,932 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [48005] [Thread-1 (wrapped_target)] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 1985
2024-11-08 14:20:12,098 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [48005] [Thread-1 (wrapped_target)] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 393
2024-11-08 14:20:12,180 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [48005] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
2024-11-08 14:20:12,182 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [48005] [sentry-sdk.BackgroundWorker] - DEBUG - Starting new HTTPS connection (1): o151352.ingest.sentry.io:443
2024-11-08 14:20:12,319 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [48005] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-08 14:37:37,542 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [48390] [MainThread] - DEBUG - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=None, shell=False, universal_newlines=False)
2024-11-08 14:37:37,555 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [48390] [MainThread] - DEBUG - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=None, shell=False, universal_newlines=False)
2024-11-08 14:37:38,001 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [48390] [Thread-1 (wrapped_target)] - DEBUG - Starting new HTTPS connection (1): api.wandb.ai:443
2024-11-08 14:37:38,204 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [48390] [Thread-1 (wrapped_target)] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 1985
2024-11-08 14:37:38,366 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [48390] [Thread-1 (wrapped_target)] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 393
2024-11-08 14:37:38,405 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [48390] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-08 14:37:43,187 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:325] [48390] [MainThread] - DEBUG - Model name detected: orange_pasta
2024-11-08 14:37:43,187 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [48390] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-08 14:37:43,187 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [48390] [MainThread] - DEBUG - Get key: cfb18a149f6039ba53a916f4842acf7761f5459f15abb1c990750760565481e4 returned value: None
2024-11-08 14:37:43,187 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:279] [48390] [MainThread] - DEBUG - ModelPath instance 2 initialized for orange_pasta.
2024-11-08 14:37:43,187 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [48390] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-08 14:37:43,187 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [48390] [MainThread] - DEBUG - Get key: cfb18a149f6039ba53a916f4842acf7761f5459f15abb1c990750760565481e4 returned value: None
2024-11-08 14:37:43,187 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:361] [48390] [MainThread] - INFO - Writing <built-in method title of str object at 0x102f86bb0>Path object to cache for model orange_pasta.
2024-11-08 14:37:43,188 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:170] [48390] [MainThread] - DEBUG - Cache saved to file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-08 14:37:43,188 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:133] [48390] [MainThread] - DEBUG - Set key: cfb18a149f6039ba53a916f4842acf7761f5459f15abb1c990750760565481e4 with value: <model_path.ModelPath object at 0x3091572d0>
2024-11-08 14:37:43,188 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:243] [48390] [MainThread] - INFO - Fetching data...
2024-11-08 14:37:43,188 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:37] [48390] [MainThread] - INFO - Beginning file download through viewser with month range 121,445
2024-11-08 14:37:43,188 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:325] [48390] [MainThread] - DEBUG - Model name detected: orange_pasta
2024-11-08 14:37:43,188 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [48390] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-08 14:37:43,188 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [48390] [MainThread] - DEBUG - Get key: 893440357c1a47ba97a9ce7646da5a99b1f2439e5a5320bfa57ea1770ca0968f returned value: <model_path.ModelPath object at 0x3091cd4d0>
2024-11-08 14:37:43,188 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:343] [48390] [MainThread] - INFO - ModelPath instance orange_pasta found in GlobalCache. Using cached instance.
2024-11-08 14:37:43,188 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:279] [48390] [MainThread] - DEBUG - ModelPath instance 3 initialized for orange_pasta.
2024-11-08 14:37:43,189 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [48390] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-08 14:37:43,189 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [48390] [MainThread] - DEBUG - Get key: 893440357c1a47ba97a9ce7646da5a99b1f2439e5a5320bfa57ea1770ca0968f returned value: <model_path.ModelPath object at 0x309191610>
2024-11-08 14:37:43,189 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:517] [48390] [MainThread] - INFO - Queryset /Users/dylanpinheiro/Desktop/views_pipeline/common_querysets/queryset_orange_pasta.py imported successfully.
2024-11-08 14:37:43,190 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:45] [48390] [MainThread] - INFO - Found queryset for orange_pasta in common_querysets
2024-11-08 14:37:43,190 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:208] [48390] [MainThread] - INFO - Publishing queryset fatalities003_pgm_baseline
2024-11-08 14:37:43,191 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [48390] [MainThread] - DEBUG - Starting new HTTPS connection (1): viewser.viewsforecasting.org:443
2024-11-08 14:37:43,531 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [48390] [MainThread] - DEBUG - https://viewser.viewsforecasting.org:443 "POST /querysets/querysets?overwrite=True HTTP/11" 200 None
2024-11-08 14:37:43,533 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:238] [48390] [MainThread] - INFO - Fetching queryset fatalities003_pgm_baseline
2024-11-08 14:37:43,538 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [48390] [MainThread] - DEBUG - Starting new HTTPS connection (1): viewser.viewsforecasting.org:443
2024-11-08 14:37:53,310 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [48390] [MainThread] - DEBUG - https://viewser.viewsforecasting.org:443 "GET /querysets/data/fatalities003_pgm_baseline?start_date=121&end_date=444 HTTP/11" 200 37032565
2024-11-08 14:38:03,480 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:56] [48390] [MainThread] - WARNING - {'orange_pasta data alert 1': ' alarm: feature zero; offender: ged_sb_dep, threshold: 0.95 Severity: 2 Timestamp: 2024-11-08 14:38:03\n, '}
2024-11-08 14:38:03,480 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:56] [48390] [MainThread] - WARNING - {'orange_pasta data alert 2': ' alarm: feature zero; offender: ln_ged_sb, threshold: 0.95 Severity: 2 Timestamp: 2024-11-08 14:38:03\n'}
2024-11-08 14:38:03,481 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_log_files.py [utils_log_files.py:57] [48390] [MainThread] - INFO - Data fetch log file created at /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/data/raw/calibration_data_fetch_log.txt
2024-11-08 14:38:03,481 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:250] [48390] [MainThread] - INFO - Saving data to /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/data/raw/calibration_viewser_df.pkl
2024-11-08 14:38:03,525 /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/src/dataloaders/get_data.py [get_data.py:12] [48390] [MainThread] - DEBUG - DataFrame shape: (4247640, 8)
2024-11-08 14:38:13,081 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [48390] [sentry-sdk.BackgroundWorker] - DEBUG - Starting new HTTPS connection (1): o151352.ingest.sentry.io:443
2024-11-08 14:38:13,238 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [48390] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-08 14:38:13,255 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [48390] [MainThread] - DEBUG - Starting new HTTPS connection (1): api.wandb.ai:443
2024-11-08 14:38:13,789 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [48390] [MainThread] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 188
2024-11-08 14:38:13,803 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [48390] [MainThread] - DEBUG - Starting new HTTPS connection (1): api.wandb.ai:443
2024-11-08 14:38:14,022 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [48390] [MainThread] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 68
2024-11-08 14:38:14,402 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [48390] [Thread-5 (_heartbeat)] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 518
2024-11-08 14:38:15,134 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [48390] [Thread-6 (_run_job)] - DEBUG - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=None, shell=False, universal_newlines=False)
2024-11-08 14:38:15,158 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [48390] [Thread-6 (_run_job)] - DEBUG - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=None, shell=False, universal_newlines=False)
2024-11-08 14:38:15,609 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [48390] [Thread-7 (wrapped_target)] - DEBUG - Starting new HTTPS connection (1): api.wandb.ai:443
2024-11-08 14:38:15,783 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [48390] [Thread-7 (wrapped_target)] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 1985
2024-11-08 14:38:15,942 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [48390] [Thread-7 (wrapped_target)] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 393
2024-11-08 14:38:15,973 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [48390] [Thread-6 (_run_job)] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-08 14:38:19,563 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [48390] [Thread-5 (_heartbeat)] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 57
2024-11-08 14:38:20,720 /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/src/management/execute_model_tasks.py [execute_model_tasks.py:50] [48390] [Thread-6 (_run_job)] - INFO - Sweeping model orange_pasta...
2024-11-08 14:38:20,720 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:325] [48390] [Thread-6 (_run_job)] - DEBUG - Model name detected: orange_pasta
2024-11-08 14:38:20,720 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [48390] [Thread-6 (_run_job)] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-08 14:38:20,720 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [48390] [Thread-6 (_run_job)] - DEBUG - Get key: 893440357c1a47ba97a9ce7646da5a99b1f2439e5a5320bfa57ea1770ca0968f returned value: <model_path.ModelPath object at 0x308537450>
2024-11-08 14:38:20,720 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:343] [48390] [Thread-6 (_run_job)] - INFO - ModelPath instance orange_pasta found in GlobalCache. Using cached instance.
2024-11-08 14:38:20,721 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:279] [48390] [Thread-6 (_run_job)] - DEBUG - ModelPath instance 4 initialized for orange_pasta.
2024-11-08 14:38:20,721 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [48390] [Thread-6 (_run_job)] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-08 14:38:20,721 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [48390] [Thread-6 (_run_job)] - DEBUG - Get key: 893440357c1a47ba97a9ce7646da5a99b1f2439e5a5320bfa57ea1770ca0968f returned value: <model_path.ModelPath object at 0x3084b6810>
2024-11-08 14:38:20,833 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/darts/timeseries.py [timeseries.py:821] [48390] [Thread-6 (_run_job)] - WARNING - UserWarning: `time_col` was not set and `df` has a monotonically increasing (time) index. This results in time series groups with non-overlapping (time) index. You can ignore this warning if the index represents the actual index of each individual time series group.
2024-11-08 14:38:24,756 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [48390] [Thread-5 (_heartbeat)] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 57
2024-11-08 14:38:25,563 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:225] [48390] [MainThread] - INFO - SIGINT received. Deleting cache file...
2024-11-08 14:38:25,581 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [48390] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
2024-11-08 14:39:03,039 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [48570] [MainThread] - DEBUG - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=None, shell=False, universal_newlines=False)
2024-11-08 14:39:03,052 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [48570] [MainThread] - DEBUG - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=None, shell=False, universal_newlines=False)
2024-11-08 14:39:03,499 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [48570] [Thread-1 (wrapped_target)] - DEBUG - Starting new HTTPS connection (1): api.wandb.ai:443
2024-11-08 14:39:03,689 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [48570] [Thread-1 (wrapped_target)] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 1985
2024-11-08 14:39:03,854 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [48570] [Thread-1 (wrapped_target)] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 393
2024-11-08 14:39:03,855 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:308] [48570] [MainThread] - DEBUG - Path input detected: /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/main.py
2024-11-08 14:39:03,855 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:202] [48570] [MainThread] - INFO - Extracting model name from Path: /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/main.py
2024-11-08 14:39:03,855 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:207] [48570] [MainThread] - INFO - Valid model name orange_pasta found in path /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/main.py
2024-11-08 14:39:03,855 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:312] [48570] [MainThread] - DEBUG - Model name extracted from path: orange_pasta
2024-11-08 14:39:03,855 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [48570] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-08 14:39:03,855 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [48570] [MainThread] - DEBUG - Get key: 893440357c1a47ba97a9ce7646da5a99b1f2439e5a5320bfa57ea1770ca0968f returned value: <model_path.ModelPath object at 0x30bfd6d90>
2024-11-08 14:39:03,855 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:343] [48570] [MainThread] - INFO - ModelPath instance orange_pasta found in GlobalCache. Using cached instance.
2024-11-08 14:39:03,856 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:279] [48570] [MainThread] - DEBUG - ModelPath instance 1 initialized for orange_pasta.
2024-11-08 14:39:03,856 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [48570] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-08 14:39:03,856 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [48570] [MainThread] - DEBUG - Get key: 893440357c1a47ba97a9ce7646da5a99b1f2439e5a5320bfa57ea1770ca0968f returned value: <model_path.ModelPath object at 0x30bf59a50>
2024-11-08 14:39:03,874 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [48570] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-08 14:39:08,559 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:283] [48570] [MainThread] - INFO - Fetching data from viewser...
2024-11-08 14:39:08,559 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:115] [48570] [MainThread] - INFO - Beginning file download through viewser with month range 121,445
2024-11-08 14:39:08,560 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:517] [48570] [MainThread] - INFO - Queryset /Users/dylanpinheiro/Desktop/views_pipeline/common_querysets/queryset_orange_pasta.py imported successfully.
2024-11-08 14:39:08,561 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:125] [48570] [MainThread] - INFO - Found queryset for orange_pasta in common_querysets
2024-11-08 14:39:08,561 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:208] [48570] [MainThread] - INFO - Publishing queryset fatalities003_pgm_baseline
2024-11-08 14:39:08,562 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [48570] [MainThread] - DEBUG - Starting new HTTPS connection (1): viewser.viewsforecasting.org:443
2024-11-08 14:39:08,920 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [48570] [MainThread] - DEBUG - https://viewser.viewsforecasting.org:443 "POST /querysets/querysets?overwrite=True HTTP/11" 200 None
2024-11-08 14:39:08,921 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:238] [48570] [MainThread] - INFO - Fetching queryset fatalities003_pgm_baseline
2024-11-08 14:39:08,922 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [48570] [MainThread] - DEBUG - Starting new HTTPS connection (1): viewser.viewsforecasting.org:443
2024-11-08 14:39:19,266 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [48570] [MainThread] - DEBUG - https://viewser.viewsforecasting.org:443 "GET /querysets/data/fatalities003_pgm_baseline?start_date=121&end_date=444 HTTP/11" 200 37032565
2024-11-08 14:39:29,350 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:140] [48570] [MainThread] - WARNING - {'orange_pasta data alert 1': ' alarm: feature zero; offender: ged_sb_dep, threshold: 0.95 Severity: 2 Timestamp: 2024-11-08 14:39:29\n, '}
2024-11-08 14:39:29,351 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:140] [48570] [MainThread] - WARNING - {'orange_pasta data alert 2': ' alarm: feature zero; offender: ln_ged_sb, threshold: 0.95 Severity: 2 Timestamp: 2024-11-08 14:39:29\n'}
2024-11-08 14:39:29,351 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_log_files.py [utils_log_files.py:57] [48570] [MainThread] - INFO - Data fetch log file created at /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/data/raw/calibration_data_fetch_log.txt
2024-11-08 14:39:29,351 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:291] [48570] [MainThread] - INFO - Saving data to /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/data/raw/calibration_viewser_df.pkl
2024-11-08 14:39:37,578 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [48570] [sentry-sdk.BackgroundWorker] - DEBUG - Starting new HTTPS connection (1): o151352.ingest.sentry.io:443
2024-11-08 14:39:37,656 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [48570] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-08 14:39:39,653 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [48570] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
2024-11-08 14:40:22,914 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [48686] [MainThread] - DEBUG - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=None, shell=False, universal_newlines=False)
2024-11-08 14:40:22,928 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [48686] [MainThread] - DEBUG - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=None, shell=False, universal_newlines=False)
2024-11-08 14:40:23,371 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [48686] [Thread-1 (wrapped_target)] - DEBUG - Starting new HTTPS connection (1): api.wandb.ai:443
2024-11-08 14:40:23,558 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [48686] [Thread-1 (wrapped_target)] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 1985
2024-11-08 14:40:23,717 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [48686] [Thread-1 (wrapped_target)] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 393
2024-11-08 14:40:23,722 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:308] [48686] [MainThread] - DEBUG - Path input detected: /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/main.py
2024-11-08 14:40:23,722 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:202] [48686] [MainThread] - INFO - Extracting model name from Path: /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/main.py
2024-11-08 14:40:23,722 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:207] [48686] [MainThread] - INFO - Valid model name orange_pasta found in path /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/main.py
2024-11-08 14:40:23,722 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:312] [48686] [MainThread] - DEBUG - Model name extracted from path: orange_pasta
2024-11-08 14:40:23,723 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [48686] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-08 14:40:23,723 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [48686] [MainThread] - DEBUG - Get key: 893440357c1a47ba97a9ce7646da5a99b1f2439e5a5320bfa57ea1770ca0968f returned value: <model_path.ModelPath object at 0x31a4d6e50>
2024-11-08 14:40:23,723 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:343] [48686] [MainThread] - INFO - ModelPath instance orange_pasta found in GlobalCache. Using cached instance.
2024-11-08 14:40:23,725 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:279] [48686] [MainThread] - DEBUG - ModelPath instance 1 initialized for orange_pasta.
2024-11-08 14:40:23,725 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [48686] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-08 14:40:23,725 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [48686] [MainThread] - DEBUG - Get key: 893440357c1a47ba97a9ce7646da5a99b1f2439e5a5320bfa57ea1770ca0968f returned value: <model_path.ModelPath object at 0x31a459f90>
2024-11-08 14:40:23,758 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [48686] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-08 14:40:28,425 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:283] [48686] [MainThread] - INFO - Fetching data from viewser...
2024-11-08 14:40:28,425 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:115] [48686] [MainThread] - INFO - Beginning file download through viewser with month range 121,445
2024-11-08 14:40:28,425 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:517] [48686] [MainThread] - INFO - Queryset /Users/dylanpinheiro/Desktop/views_pipeline/common_querysets/queryset_orange_pasta.py imported successfully.
2024-11-08 14:40:28,426 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:125] [48686] [MainThread] - INFO - Found queryset for orange_pasta in common_querysets
2024-11-08 14:40:28,426 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:208] [48686] [MainThread] - INFO - Publishing queryset fatalities003_pgm_baseline
2024-11-08 14:40:28,427 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [48686] [MainThread] - DEBUG - Starting new HTTPS connection (1): viewser.viewsforecasting.org:443
2024-11-08 14:40:28,786 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [48686] [MainThread] - DEBUG - https://viewser.viewsforecasting.org:443 "POST /querysets/querysets?overwrite=True HTTP/11" 200 None
2024-11-08 14:40:28,788 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:238] [48686] [MainThread] - INFO - Fetching queryset fatalities003_pgm_baseline
2024-11-08 14:40:28,793 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [48686] [MainThread] - DEBUG - Starting new HTTPS connection (1): viewser.viewsforecasting.org:443
2024-11-08 14:40:38,789 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [48686] [MainThread] - DEBUG - https://viewser.viewsforecasting.org:443 "GET /querysets/data/fatalities003_pgm_baseline?start_date=121&end_date=444 HTTP/11" 200 37032565
2024-11-08 14:40:49,204 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:140] [48686] [MainThread] - WARNING - {'orange_pasta data alert 1': ' alarm: feature zero; offender: ged_sb_dep, threshold: 0.95 Severity: 2 Timestamp: 2024-11-08 14:40:49\n, '}
2024-11-08 14:40:49,205 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:140] [48686] [MainThread] - WARNING - {'orange_pasta data alert 2': ' alarm: feature zero; offender: ln_ged_sb, threshold: 0.95 Severity: 2 Timestamp: 2024-11-08 14:40:49\n'}
2024-11-08 14:40:49,205 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_log_files.py [utils_log_files.py:57] [48686] [MainThread] - INFO - Data fetch log file created at /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/data/raw/calibration_data_fetch_log.txt
2024-11-08 14:40:49,205 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:291] [48686] [MainThread] - INFO - Saving data to /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/data/raw/calibration_viewser_df.pkl
2024-11-08 14:40:54,272 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [48686] [sentry-sdk.BackgroundWorker] - DEBUG - Starting new HTTPS connection (1): o151352.ingest.sentry.io:443
2024-11-08 14:40:54,352 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [48686] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-08 14:40:54,366 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [48686] [MainThread] - DEBUG - Starting new HTTPS connection (1): api.wandb.ai:443
2024-11-08 14:40:55,683 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [48686] [MainThread] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 202
2024-11-08 14:40:55,703 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [48686] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-08 14:41:13,235 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [48686] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-08 14:41:15,270 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [48686] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
2024-11-08 14:45:39,452 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [48875] [MainThread] - DEBUG - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=None, shell=False, universal_newlines=False)
2024-11-08 14:45:39,465 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [48875] [MainThread] - DEBUG - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=None, shell=False, universal_newlines=False)
2024-11-08 14:45:39,910 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [48875] [Thread-1 (wrapped_target)] - DEBUG - Starting new HTTPS connection (1): api.wandb.ai:443
2024-11-08 14:45:40,111 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [48875] [Thread-1 (wrapped_target)] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 1985
2024-11-08 14:45:40,267 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [48875] [Thread-1 (wrapped_target)] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 393
2024-11-08 14:45:40,268 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:308] [48875] [MainThread] - DEBUG - Path input detected: /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/main.py
2024-11-08 14:45:40,269 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:202] [48875] [MainThread] - INFO - Extracting model name from Path: /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/main.py
2024-11-08 14:45:40,269 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:207] [48875] [MainThread] - INFO - Valid model name orange_pasta found in path /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/main.py
2024-11-08 14:45:40,269 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:312] [48875] [MainThread] - DEBUG - Model name extracted from path: orange_pasta
2024-11-08 14:45:40,269 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [48875] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-08 14:45:40,269 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [48875] [MainThread] - DEBUG - Get key: 893440357c1a47ba97a9ce7646da5a99b1f2439e5a5320bfa57ea1770ca0968f returned value: <model_path.ModelPath object at 0x3136577d0>
2024-11-08 14:45:40,269 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:343] [48875] [MainThread] - INFO - ModelPath instance orange_pasta found in GlobalCache. Using cached instance.
2024-11-08 14:45:40,269 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:279] [48875] [MainThread] - DEBUG - ModelPath instance 1 initialized for orange_pasta.
2024-11-08 14:45:40,270 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [48875] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-08 14:45:40,270 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [48875] [MainThread] - DEBUG - Get key: 893440357c1a47ba97a9ce7646da5a99b1f2439e5a5320bfa57ea1770ca0968f returned value: <model_path.ModelPath object at 0x313652e50>
2024-11-08 14:45:40,290 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [48875] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-08 14:45:45,153 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:283] [48875] [MainThread] - INFO - Fetching data from viewser...
2024-11-08 14:45:45,154 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:115] [48875] [MainThread] - INFO - Beginning file download through viewser with month range 121,445
2024-11-08 14:45:45,154 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:517] [48875] [MainThread] - INFO - Queryset /Users/dylanpinheiro/Desktop/views_pipeline/common_querysets/queryset_orange_pasta.py imported successfully.
2024-11-08 14:45:45,155 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:125] [48875] [MainThread] - INFO - Found queryset for orange_pasta in common_querysets
2024-11-08 14:45:45,155 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:208] [48875] [MainThread] - INFO - Publishing queryset fatalities003_pgm_baseline
2024-11-08 14:45:45,156 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [48875] [MainThread] - DEBUG - Starting new HTTPS connection (1): viewser.viewsforecasting.org:443
2024-11-08 14:45:45,508 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [48875] [MainThread] - DEBUG - https://viewser.viewsforecasting.org:443 "POST /querysets/querysets?overwrite=True HTTP/11" 200 None
2024-11-08 14:45:45,508 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:238] [48875] [MainThread] - INFO - Fetching queryset fatalities003_pgm_baseline
2024-11-08 14:45:45,511 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [48875] [MainThread] - DEBUG - Starting new HTTPS connection (1): viewser.viewsforecasting.org:443
2024-11-08 14:45:55,051 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [48875] [MainThread] - DEBUG - https://viewser.viewsforecasting.org:443 "GET /querysets/data/fatalities003_pgm_baseline?start_date=121&end_date=444 HTTP/11" 200 37032565
2024-11-08 14:46:05,081 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:140] [48875] [MainThread] - WARNING - {'orange_pasta data alert 1': ' alarm: feature zero; offender: ged_sb_dep, threshold: 0.95 Severity: 2 Timestamp: 2024-11-08 14:46:05\n, '}
2024-11-08 14:46:05,081 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:140] [48875] [MainThread] - WARNING - {'orange_pasta data alert 2': ' alarm: feature zero; offender: ln_ged_sb, threshold: 0.95 Severity: 2 Timestamp: 2024-11-08 14:46:05\n'}
2024-11-08 14:46:05,082 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_log_files.py [utils_log_files.py:57] [48875] [MainThread] - INFO - Data fetch log file created at /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/data/raw/calibration_data_fetch_log.txt
2024-11-08 14:46:05,082 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:291] [48875] [MainThread] - INFO - Saving data to /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/data/raw/calibration_viewser_df.pkl
2024-11-08 14:46:12,990 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [48875] [sentry-sdk.BackgroundWorker] - DEBUG - Starting new HTTPS connection (1): o151352.ingest.sentry.io:443
2024-11-08 14:46:13,086 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [48875] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-08 14:46:13,099 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [48875] [MainThread] - DEBUG - Starting new HTTPS connection (1): api.wandb.ai:443
2024-11-08 14:46:14,608 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [48875] [MainThread] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 202
2024-11-08 14:46:14,635 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [48875] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-08 14:46:27,081 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [48875] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-08 14:46:29,121 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [48875] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
2024-11-08 14:51:18,725 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [49141] [MainThread] - DEBUG - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=None, shell=False, universal_newlines=False)
2024-11-08 14:51:18,739 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [49141] [MainThread] - DEBUG - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=None, shell=False, universal_newlines=False)
2024-11-08 14:51:19,187 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [49141] [Thread-1 (wrapped_target)] - DEBUG - Starting new HTTPS connection (1): api.wandb.ai:443
2024-11-08 14:51:19,417 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [49141] [Thread-1 (wrapped_target)] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 1985
2024-11-08 14:51:19,575 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [49141] [Thread-1 (wrapped_target)] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 393
2024-11-08 14:51:19,580 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:308] [49141] [MainThread] - DEBUG - Path input detected: /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/main.py
2024-11-08 14:51:19,580 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:202] [49141] [MainThread] - INFO - Extracting model name from Path: /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/main.py
2024-11-08 14:51:19,580 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:207] [49141] [MainThread] - INFO - Valid model name orange_pasta found in path /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/main.py
2024-11-08 14:51:19,580 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:312] [49141] [MainThread] - DEBUG - Model name extracted from path: orange_pasta
2024-11-08 14:51:19,581 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [49141] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-08 14:51:19,581 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [49141] [MainThread] - DEBUG - Get key: 893440357c1a47ba97a9ce7646da5a99b1f2439e5a5320bfa57ea1770ca0968f returned value: <model_path.ModelPath object at 0x314a0bb90>
2024-11-08 14:51:19,581 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:343] [49141] [MainThread] - INFO - ModelPath instance orange_pasta found in GlobalCache. Using cached instance.
2024-11-08 14:51:19,581 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:279] [49141] [MainThread] - DEBUG - ModelPath instance 1 initialized for orange_pasta.
2024-11-08 14:51:19,582 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [49141] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-08 14:51:19,582 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [49141] [MainThread] - DEBUG - Get key: 893440357c1a47ba97a9ce7646da5a99b1f2439e5a5320bfa57ea1770ca0968f returned value: <model_path.ModelPath object at 0x314c5d990>
2024-11-08 14:51:19,606 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [49141] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-08 14:51:24,388 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:283] [49141] [MainThread] - INFO - Fetching data from viewser...
2024-11-08 14:51:24,388 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:115] [49141] [MainThread] - INFO - Beginning file download through viewser with month range 121,445
2024-11-08 14:51:24,388 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:517] [49141] [MainThread] - INFO - Queryset /Users/dylanpinheiro/Desktop/views_pipeline/common_querysets/queryset_orange_pasta.py imported successfully.
2024-11-08 14:51:24,389 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:125] [49141] [MainThread] - INFO - Found queryset for orange_pasta in common_querysets
2024-11-08 14:51:24,390 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:208] [49141] [MainThread] - INFO - Publishing queryset fatalities003_pgm_baseline
2024-11-08 14:51:24,391 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [49141] [MainThread] - DEBUG - Starting new HTTPS connection (1): viewser.viewsforecasting.org:443
2024-11-08 14:51:24,752 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [49141] [MainThread] - DEBUG - https://viewser.viewsforecasting.org:443 "POST /querysets/querysets?overwrite=True HTTP/11" 200 None
2024-11-08 14:51:24,754 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:238] [49141] [MainThread] - INFO - Fetching queryset fatalities003_pgm_baseline
2024-11-08 14:51:24,759 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [49141] [MainThread] - DEBUG - Starting new HTTPS connection (1): viewser.viewsforecasting.org:443
2024-11-08 14:51:34,093 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [49141] [MainThread] - DEBUG - https://viewser.viewsforecasting.org:443 "GET /querysets/data/fatalities003_pgm_baseline?start_date=121&end_date=444 HTTP/11" 200 37032565
2024-11-08 14:51:44,359 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:140] [49141] [MainThread] - WARNING - {'orange_pasta data alert 1': ' alarm: feature zero; offender: ged_sb_dep, threshold: 0.95 Severity: 2 Timestamp: 2024-11-08 14:51:44\n, '}
2024-11-08 14:51:44,360 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:140] [49141] [MainThread] - WARNING - {'orange_pasta data alert 2': ' alarm: feature zero; offender: ln_ged_sb, threshold: 0.95 Severity: 2 Timestamp: 2024-11-08 14:51:44\n'}
2024-11-08 14:51:44,360 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_log_files.py [utils_log_files.py:57] [49141] [MainThread] - INFO - Data fetch log file created at /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/data/raw/calibration_data_fetch_log.txt
2024-11-08 14:51:44,360 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:291] [49141] [MainThread] - INFO - Saving data to /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/data/raw/calibration_viewser_df.pkl
2024-11-08 14:51:51,150 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [49141] [sentry-sdk.BackgroundWorker] - DEBUG - Starting new HTTPS connection (1): o151352.ingest.sentry.io:443
2024-11-08 14:51:51,238 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [49141] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-08 14:51:51,245 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [49141] [MainThread] - DEBUG - Starting new HTTPS connection (1): api.wandb.ai:443
2024-11-08 14:51:51,683 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [49141] [MainThread] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 202
2024-11-08 14:51:51,714 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [49141] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-08 14:52:05,053 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [49141] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-08 14:52:07,088 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [49141] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
2024-11-08 15:15:25,081 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [49779] [MainThread] - DEBUG - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=None, shell=False, universal_newlines=False)
2024-11-08 15:15:25,094 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [49779] [MainThread] - DEBUG - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=None, shell=False, universal_newlines=False)
2024-11-08 15:15:25,542 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [49779] [Thread-1 (wrapped_target)] - DEBUG - Starting new HTTPS connection (1): api.wandb.ai:443
2024-11-08 15:15:25,740 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [49779] [Thread-1 (wrapped_target)] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 1985
2024-11-08 15:15:25,901 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [49779] [Thread-1 (wrapped_target)] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 393
2024-11-08 15:15:25,906 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:308] [49779] [MainThread] - DEBUG - Path input detected: /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/main.py
2024-11-08 15:15:25,906 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:202] [49779] [MainThread] - INFO - Extracting model name from Path: /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/main.py
2024-11-08 15:15:25,907 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:207] [49779] [MainThread] - INFO - Valid model name orange_pasta found in path /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/main.py
2024-11-08 15:15:25,907 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:312] [49779] [MainThread] - DEBUG - Model name extracted from path: orange_pasta
2024-11-08 15:15:25,908 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [49779] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-08 15:15:25,908 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [49779] [MainThread] - DEBUG - Get key: 893440357c1a47ba97a9ce7646da5a99b1f2439e5a5320bfa57ea1770ca0968f returned value: <model_path.ModelPath object at 0x30c06f450>
2024-11-08 15:15:25,908 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:343] [49779] [MainThread] - INFO - ModelPath instance orange_pasta found in GlobalCache. Using cached instance.
2024-11-08 15:15:25,909 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:279] [49779] [MainThread] - DEBUG - ModelPath instance 1 initialized for orange_pasta.
2024-11-08 15:15:25,910 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [49779] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-08 15:15:25,910 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [49779] [MainThread] - DEBUG - Get key: 893440357c1a47ba97a9ce7646da5a99b1f2439e5a5320bfa57ea1770ca0968f returned value: <model_path.ModelPath object at 0x30c057410>
2024-11-08 15:15:25,942 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [49779] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-08 15:15:30,763 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:283] [49779] [MainThread] - INFO - Fetching data from viewser...
2024-11-08 15:15:30,763 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:115] [49779] [MainThread] - INFO - Beginning file download through viewser with month range 121,445
2024-11-08 15:15:30,763 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:517] [49779] [MainThread] - INFO - Queryset /Users/dylanpinheiro/Desktop/views_pipeline/common_querysets/queryset_orange_pasta.py imported successfully.
2024-11-08 15:15:30,764 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:125] [49779] [MainThread] - INFO - Found queryset for orange_pasta in common_querysets
2024-11-08 15:15:30,764 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:208] [49779] [MainThread] - INFO - Publishing queryset fatalities003_pgm_baseline
2024-11-08 15:15:30,766 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [49779] [MainThread] - DEBUG - Starting new HTTPS connection (1): viewser.viewsforecasting.org:443
2024-11-08 15:15:31,131 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [49779] [MainThread] - DEBUG - https://viewser.viewsforecasting.org:443 "POST /querysets/querysets?overwrite=True HTTP/11" 200 None
2024-11-08 15:15:31,133 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:238] [49779] [MainThread] - INFO - Fetching queryset fatalities003_pgm_baseline
2024-11-08 15:15:31,137 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [49779] [MainThread] - DEBUG - Starting new HTTPS connection (1): viewser.viewsforecasting.org:443
2024-11-08 15:15:40,840 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [49779] [MainThread] - DEBUG - https://viewser.viewsforecasting.org:443 "GET /querysets/data/fatalities003_pgm_baseline?start_date=121&end_date=444 HTTP/11" 200 37032565
2024-11-08 15:15:50,296 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:140] [49779] [MainThread] - WARNING - {'orange_pasta data alert 1': ' alarm: feature zero; offender: ged_sb_dep, threshold: 0.95 Severity: 2 Timestamp: 2024-11-08 15:15:50\n, '}
2024-11-08 15:15:50,296 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:140] [49779] [MainThread] - WARNING - {'orange_pasta data alert 2': ' alarm: feature zero; offender: ln_ged_sb, threshold: 0.95 Severity: 2 Timestamp: 2024-11-08 15:15:50\n'}
2024-11-08 15:15:50,296 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_log_files.py [utils_log_files.py:57] [49779] [MainThread] - INFO - Data fetch log file created at /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/data/raw/calibration_data_fetch_log.txt
2024-11-08 15:15:50,296 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:291] [49779] [MainThread] - INFO - Saving data to /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/data/raw/calibration_viewser_df.pkl
2024-11-08 15:15:56,799 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [49779] [sentry-sdk.BackgroundWorker] - DEBUG - Starting new HTTPS connection (1): o151352.ingest.sentry.io:443
2024-11-08 15:15:56,889 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [49779] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-08 15:15:56,914 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [49779] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-08 15:16:08,612 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [49779] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-08 15:16:08,639 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [49779] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-08 15:16:15,461 /Users/dylanpinheiro/Desktop/views_pipeline/model_manager.py [model_manager.py:317] [49779] [MainThread] - INFO - Training model orange_pasta...
2024-11-08 15:16:23,257 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [49779] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-08 15:16:24,982 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [49779] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
2024-11-08 15:17:01,058 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [49956] [MainThread] - DEBUG - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=None, shell=False, universal_newlines=False)
2024-11-08 15:17:01,071 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [49956] [MainThread] - DEBUG - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=None, shell=False, universal_newlines=False)
2024-11-08 15:17:01,513 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [49956] [Thread-1 (wrapped_target)] - DEBUG - Starting new HTTPS connection (1): api.wandb.ai:443
2024-11-08 15:17:01,713 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [49956] [Thread-1 (wrapped_target)] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 1985
2024-11-08 15:17:01,892 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [49956] [Thread-1 (wrapped_target)] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 393
2024-11-08 15:17:01,896 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:308] [49956] [MainThread] - DEBUG - Path input detected: /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/main.py
2024-11-08 15:17:01,897 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:202] [49956] [MainThread] - INFO - Extracting model name from Path: /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/main.py
2024-11-08 15:17:01,897 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:207] [49956] [MainThread] - INFO - Valid model name orange_pasta found in path /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/main.py
2024-11-08 15:17:01,897 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:312] [49956] [MainThread] - DEBUG - Model name extracted from path: orange_pasta
2024-11-08 15:17:01,898 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [49956] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-08 15:17:01,898 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [49956] [MainThread] - DEBUG - Get key: 893440357c1a47ba97a9ce7646da5a99b1f2439e5a5320bfa57ea1770ca0968f returned value: <model_path.ModelPath object at 0x313ab9050>
2024-11-08 15:17:01,898 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:343] [49956] [MainThread] - INFO - ModelPath instance orange_pasta found in GlobalCache. Using cached instance.
2024-11-08 15:17:01,899 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:279] [49956] [MainThread] - DEBUG - ModelPath instance 1 initialized for orange_pasta.
2024-11-08 15:17:01,900 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [49956] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-08 15:17:01,900 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [49956] [MainThread] - DEBUG - Get key: 893440357c1a47ba97a9ce7646da5a99b1f2439e5a5320bfa57ea1770ca0968f returned value: <model_path.ModelPath object at 0x313c55f10>
2024-11-08 15:17:01,933 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [49956] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-08 15:17:06,608 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:283] [49956] [MainThread] - INFO - Fetching data from viewser...
2024-11-08 15:17:06,608 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:115] [49956] [MainThread] - INFO - Beginning file download through viewser with month range 121,445
2024-11-08 15:17:06,608 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:517] [49956] [MainThread] - INFO - Queryset /Users/dylanpinheiro/Desktop/views_pipeline/common_querysets/queryset_orange_pasta.py imported successfully.
2024-11-08 15:17:06,609 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:125] [49956] [MainThread] - INFO - Found queryset for orange_pasta in common_querysets
2024-11-08 15:17:06,609 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:208] [49956] [MainThread] - INFO - Publishing queryset fatalities003_pgm_baseline
2024-11-08 15:17:06,610 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [49956] [MainThread] - DEBUG - Starting new HTTPS connection (1): viewser.viewsforecasting.org:443
2024-11-08 15:17:06,966 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [49956] [MainThread] - DEBUG - https://viewser.viewsforecasting.org:443 "POST /querysets/querysets?overwrite=True HTTP/11" 200 None
2024-11-08 15:17:06,968 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:238] [49956] [MainThread] - INFO - Fetching queryset fatalities003_pgm_baseline
2024-11-08 15:17:06,973 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [49956] [MainThread] - DEBUG - Starting new HTTPS connection (1): viewser.viewsforecasting.org:443
2024-11-08 15:17:16,471 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [49956] [MainThread] - DEBUG - https://viewser.viewsforecasting.org:443 "GET /querysets/data/fatalities003_pgm_baseline?start_date=121&end_date=444 HTTP/11" 200 37032565
2024-11-08 15:17:26,634 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:140] [49956] [MainThread] - WARNING - {'orange_pasta data alert 1': ' alarm: feature zero; offender: ged_sb_dep, threshold: 0.95 Severity: 2 Timestamp: 2024-11-08 15:17:26\n, '}
2024-11-08 15:17:26,635 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:140] [49956] [MainThread] - WARNING - {'orange_pasta data alert 2': ' alarm: feature zero; offender: ln_ged_sb, threshold: 0.95 Severity: 2 Timestamp: 2024-11-08 15:17:26\n'}
2024-11-08 15:17:26,635 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_log_files.py [utils_log_files.py:57] [49956] [MainThread] - INFO - Data fetch log file created at /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/data/raw/calibration_data_fetch_log.txt
2024-11-08 15:17:26,635 /Users/dylanpinheiro/Desktop/views_pipeline/views_dataloader.py [views_dataloader.py:291] [49956] [MainThread] - INFO - Saving data to /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/data/raw/calibration_viewser_df.pkl
2024-11-08 15:17:33,664 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [49956] [sentry-sdk.BackgroundWorker] - DEBUG - Starting new HTTPS connection (1): o151352.ingest.sentry.io:443
2024-11-08 15:17:33,809 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [49956] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-08 15:17:33,839 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [49956] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-08 15:17:45,795 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [49956] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-08 15:17:45,823 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [49956] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-08 15:17:51,614 /Users/dylanpinheiro/Desktop/views_pipeline/model_manager.py [model_manager.py:317] [49956] [MainThread] - INFO - Training model orange_pasta...
2024-11-08 15:17:51,674 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/darts/timeseries.py [timeseries.py:821] [49956] [MainThread] - WARNING - UserWarning: `time_col` was not set and `df` has a monotonically increasing (time) index. This results in time series groups with non-overlapping (time) index. You can ignore this warning if the index represents the actual index of each individual time series group.
2024-11-08 15:19:45,739 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_log_files.py [utils_log_files.py:119] [49956] [MainThread] - INFO - Log file created at /Users/dylanpinheiro/Desktop/views_pipeline/models/orange_pasta/data/generated/calibration_log.txt
2024-11-08 15:19:45,740 /Users/dylanpinheiro/Desktop/views_pipeline/model_manager.py [model_manager.py:330] [49956] [MainThread] - INFO - Done. Runtime: 1.902 minutes.

2024-11-08 15:19:50,906 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [49956] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-08 15:19:50,925 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [49956] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-08 15:20:04,398 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [49956] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-08 15:20:04,668 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [49956] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-08 15:20:19,088 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [49956] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-08 15:20:19,117 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [49956] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-08 15:20:30,657 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [49956] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-08 15:20:32,582 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [49956] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
