2024-11-07 11:57:08,336 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:361] [26592] [MainThread] - INFO - Writing <built-in method title of str object at 0x102462c30>Path object to cache for model lavender_haze.
2024-11-07 11:57:08,337 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:243] [26592] [MainThread] - INFO - Fetching data...
2024-11-07 11:57:08,337 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:37] [26592] [MainThread] - INFO - Beginning file download through viewser with month range 121,445
2024-11-07 11:57:08,337 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:343] [26592] [MainThread] - INFO - ModelPath instance lavender_haze found in GlobalCache. Using cached instance.
2024-11-07 11:57:08,339 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:505] [26592] [MainThread] - INFO - Queryset /Users/dylanpinheiro/Desktop/views_pipeline/common_querysets/queryset_lavender_haze.py imported successfully.
2024-11-07 11:57:08,344 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:45] [26592] [MainThread] - INFO - Found queryset for lavender_haze in common_querysets
2024-11-07 11:57:08,344 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:208] [26592] [MainThread] - INFO - Publishing queryset fatalities003_pgm_broad
2024-11-07 11:57:09,010 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:238] [26592] [MainThread] - INFO - Fetching queryset fatalities003_pgm_broad
2024-11-07 11:57:39,467 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:225] [26592] [MainThread] - INFO - SIGINT received. Deleting cache file...
2024-11-07 11:57:39,469 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [26592] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
2024-11-07 12:00:26,699 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:225] [26971] [MainThread] - INFO - SIGINT received. Deleting cache file...
2024-11-07 12:00:26,699 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [26971] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
2024-11-07 12:01:41,473 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [27104] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
2024-11-07 12:03:14,805 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:202] [27238] [MainThread] - INFO - Extracting model name from Path: /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/dataloaders/get_data.py
2024-11-07 12:03:14,805 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:207] [27238] [MainThread] - INFO - Valid model name lavender_haze found in path /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/dataloaders/get_data.py
2024-11-07 12:03:14,805 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:343] [27238] [MainThread] - INFO - ModelPath instance lavender_haze found in GlobalCache. Using cached instance.
2024-11-07 12:03:22,795 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:225] [27238] [MainThread] - INFO - SIGINT received. Deleting cache file...
2024-11-07 12:03:22,797 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [27238] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
2024-11-07 12:04:03,590 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:202] [27341] [MainThread] - INFO - Extracting model name from Path: /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/dataloaders/get_data.py
2024-11-07 12:04:03,590 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:207] [27341] [MainThread] - INFO - Valid model name lavender_haze found in path /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/dataloaders/get_data.py
2024-11-07 12:04:03,591 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:343] [27341] [MainThread] - INFO - ModelPath instance lavender_haze found in GlobalCache. Using cached instance.
2024-11-07 12:04:03,591 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:249] [27341] [MainThread] - INFO - Fetching data...
2024-11-07 12:04:03,591 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:98] [27341] [MainThread] - INFO - Beginning file download through viewser with month range 121,445
2024-11-07 12:04:03,592 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:505] [27341] [MainThread] - INFO - Queryset /Users/dylanpinheiro/Desktop/views_pipeline/common_querysets/queryset_lavender_haze.py imported successfully.
2024-11-07 12:04:03,596 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:108] [27341] [MainThread] - INFO - Found queryset for lavender_haze in common_querysets
2024-11-07 12:04:03,596 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:208] [27341] [MainThread] - INFO - Publishing queryset fatalities003_pgm_broad
2024-11-07 12:04:04,231 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:238] [27341] [MainThread] - INFO - Fetching queryset fatalities003_pgm_broad
2024-11-07 12:04:46,050 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:125] [27341] [MainThread] - WARNING - {'lavender_haze data alert 1': ' alarm: feature zero; offender: ln_ged_sb_dep, threshold: 0.95 Severity: 2 Timestamp: 2024-11-07 12:04:45\n, '}
2024-11-07 12:04:46,051 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:125] [27341] [MainThread] - WARNING - {'lavender_haze data alert 2': ' alarm: feature zero; offender: ged_sb, threshold: 0.95 Severity: 2 Timestamp: 2024-11-07 12:04:45\n, '}
2024-11-07 12:04:46,051 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:125] [27341] [MainThread] - WARNING - {'lavender_haze data alert 3': ' alarm: feature zero; offender: ged_os, threshold: 0.95 Severity: 2 Timestamp: 2024-11-07 12:04:45\n, '}
2024-11-07 12:04:46,051 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:125] [27341] [MainThread] - WARNING - {'lavender_haze data alert 4': ' alarm: feature zero; offender: ged_ns, threshold: 0.95 Severity: 2 Timestamp: 2024-11-07 12:04:45\n'}
2024-11-07 12:04:46,052 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_log_files.py [utils_log_files.py:57] [27341] [MainThread] - INFO - Data fetch log file created at /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/data/raw/calibration_data_fetch_log.txt
2024-11-07 12:04:46,052 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:256] [27341] [MainThread] - INFO - Saving data to /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/data/raw/calibration_viewser_df.pkl
2024-11-07 12:04:46,160 /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/dataloaders/get_data.py [get_data.py:17] [27341] [MainThread] - WARNING - {'calibration data alert 1': ' alarm: feature zero; offender: ln_ged_sb_dep, threshold: 0.95 Severity: 2 Timestamp: 2024-11-07 12:04:45\n, '}
2024-11-07 12:04:46,160 /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/dataloaders/get_data.py [get_data.py:17] [27341] [MainThread] - WARNING - {'calibration data alert 2': ' alarm: feature zero; offender: ged_sb, threshold: 0.95 Severity: 2 Timestamp: 2024-11-07 12:04:45\n, '}
2024-11-07 12:04:46,160 /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/dataloaders/get_data.py [get_data.py:17] [27341] [MainThread] - WARNING - {'calibration data alert 3': ' alarm: feature zero; offender: ged_os, threshold: 0.95 Severity: 2 Timestamp: 2024-11-07 12:04:45\n, '}
2024-11-07 12:04:46,161 /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/dataloaders/get_data.py [get_data.py:17] [27341] [MainThread] - WARNING - {'calibration data alert 4': ' alarm: feature zero; offender: ged_ns, threshold: 0.95 Severity: 2 Timestamp: 2024-11-07 12:04:45\n'}
2024-11-07 12:04:58,424 /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_tasks.py [execute_model_tasks.py:60] [27341] [MainThread] - INFO - Training model lavender_haze...
2024-11-07 12:04:58,424 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:343] [27341] [MainThread] - INFO - ModelPath instance lavender_haze found in GlobalCache. Using cached instance.
2024-11-07 12:04:59,395 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/stepshift/stepshift.py [stepshift.py:69] [27341] [MainThread] - WARNING - Reordering feature dimension. Save memory by setting the outcome feature as the first column in your dataframe.
2024-11-07 12:06:42,625 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_log_files.py [utils_log_files.py:119] [27341] [MainThread] - INFO - Log file created at /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/data/generated/calibration_log.txt
2024-11-07 12:06:42,642 /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_tasks.py [execute_model_tasks.py:74] [27341] [MainThread] - INFO - Done. Runtime: 1.832 minutes.

2024-11-07 12:06:48,257 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [27341] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
2024-11-07 13:30:51,616 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:202] [28536] [MainThread] - INFO - Extracting model name from Path: /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_runs.py
2024-11-07 13:30:51,616 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:207] [28536] [MainThread] - INFO - Valid model name lavender_haze found in path /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_runs.py
2024-11-07 13:30:51,617 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:343] [28536] [MainThread] - INFO - ModelPath instance lavender_haze found in GlobalCache. Using cached instance.
2024-11-07 13:30:51,617 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:248] [28536] [MainThread] - INFO - Fetching data from viewser...
2024-11-07 13:30:51,617 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:96] [28536] [MainThread] - INFO - Beginning file download through viewser with month range 121,445
2024-11-07 13:30:51,617 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:505] [28536] [MainThread] - INFO - Queryset /Users/dylanpinheiro/Desktop/views_pipeline/common_querysets/queryset_lavender_haze.py imported successfully.
2024-11-07 13:30:51,622 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:106] [28536] [MainThread] - INFO - Found queryset for lavender_haze in common_querysets
2024-11-07 13:30:51,622 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:208] [28536] [MainThread] - INFO - Publishing queryset fatalities003_pgm_broad
2024-11-07 13:30:52,287 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:238] [28536] [MainThread] - INFO - Fetching queryset fatalities003_pgm_broad
2024-11-07 13:31:20,215 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:225] [28536] [MainThread] - INFO - SIGINT received. Deleting cache file...
2024-11-07 13:31:20,217 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [28536] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
2024-11-07 13:34:26,237 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:202] [28706] [MainThread] - INFO - Extracting model name from Path: /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_runs.py
2024-11-07 13:34:26,237 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:207] [28706] [MainThread] - INFO - Valid model name lavender_haze found in path /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_runs.py
2024-11-07 13:34:26,237 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:343] [28706] [MainThread] - INFO - ModelPath instance lavender_haze found in GlobalCache. Using cached instance.
2024-11-07 13:34:26,238 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:248] [28706] [MainThread] - INFO - Fetching data from viewser...
2024-11-07 13:34:26,238 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:96] [28706] [MainThread] - INFO - Beginning file download through viewser with month range 121,445
2024-11-07 13:34:26,238 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:505] [28706] [MainThread] - INFO - Queryset /Users/dylanpinheiro/Desktop/views_pipeline/common_querysets/queryset_lavender_haze.py imported successfully.
2024-11-07 13:34:26,242 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:106] [28706] [MainThread] - INFO - Found queryset for lavender_haze in common_querysets
2024-11-07 13:34:26,242 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:208] [28706] [MainThread] - INFO - Publishing queryset fatalities003_pgm_broad
2024-11-07 13:34:26,875 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:238] [28706] [MainThread] - INFO - Fetching queryset fatalities003_pgm_broad
2024-11-07 13:35:06,177 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:123] [28706] [MainThread] - WARNING - {'lavender_haze data alert 1': ' alarm: feature zero; offender: ln_ged_sb_dep, threshold: 0.95 Severity: 2 Timestamp: 2024-11-07 13:35:06\n, '}
2024-11-07 13:35:06,177 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:123] [28706] [MainThread] - WARNING - {'lavender_haze data alert 2': ' alarm: feature zero; offender: ged_sb, threshold: 0.95 Severity: 2 Timestamp: 2024-11-07 13:35:06\n, '}
2024-11-07 13:35:06,178 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:123] [28706] [MainThread] - WARNING - {'lavender_haze data alert 3': ' alarm: feature zero; offender: ged_os, threshold: 0.95 Severity: 2 Timestamp: 2024-11-07 13:35:06\n, '}
2024-11-07 13:35:06,178 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:123] [28706] [MainThread] - WARNING - {'lavender_haze data alert 4': ' alarm: feature zero; offender: ged_ns, threshold: 0.95 Severity: 2 Timestamp: 2024-11-07 13:35:06\n'}
2024-11-07 13:35:06,178 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_log_files.py [utils_log_files.py:57] [28706] [MainThread] - INFO - Data fetch log file created at /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/data/raw/calibration_data_fetch_log.txt
2024-11-07 13:35:06,178 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:252] [28706] [MainThread] - INFO - Saving data to /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/data/raw/calibration_viewser_df.pkl
2024-11-07 13:35:17,985 /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_tasks.py [execute_model_tasks.py:60] [28706] [MainThread] - INFO - Training model lavender_haze...
2024-11-07 13:35:17,986 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:343] [28706] [MainThread] - INFO - ModelPath instance lavender_haze found in GlobalCache. Using cached instance.
2024-11-07 13:35:18,922 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/stepshift/stepshift.py [stepshift.py:69] [28706] [MainThread] - WARNING - Reordering feature dimension. Save memory by setting the outcome feature as the first column in your dataframe.
2024-11-07 13:37:04,014 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_log_files.py [utils_log_files.py:119] [28706] [MainThread] - INFO - Log file created at /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/data/generated/calibration_log.txt
2024-11-07 13:37:04,032 /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_tasks.py [execute_model_tasks.py:74] [28706] [MainThread] - INFO - Done. Runtime: 1.860 minutes.

2024-11-07 13:37:10,400 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [28706] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
2024-11-07 14:33:33,916 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:225] [30767] [MainThread] - INFO - SIGINT received. Deleting cache file...
2024-11-07 14:33:33,918 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [30767] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
2024-11-07 14:34:25,633 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:202] [30875] [MainThread] - INFO - Extracting model name from Path: /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_runs.py
2024-11-07 14:34:25,633 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:207] [30875] [MainThread] - INFO - Valid model name lavender_haze found in path /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_runs.py
2024-11-07 14:34:25,634 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:343] [30875] [MainThread] - INFO - ModelPath instance lavender_haze found in GlobalCache. Using cached instance.
2024-11-07 14:34:32,183 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:225] [30875] [MainThread] - INFO - SIGINT received. Deleting cache file...
2024-11-07 14:34:32,185 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [30875] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
2024-11-07 14:35:42,503 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:202] [30972] [MainThread] - INFO - Extracting model name from Path: /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_runs.py
2024-11-07 14:35:42,503 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:207] [30972] [MainThread] - INFO - Valid model name lavender_haze found in path /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_runs.py
2024-11-07 14:35:42,503 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:343] [30972] [MainThread] - INFO - ModelPath instance lavender_haze found in GlobalCache. Using cached instance.
2024-11-07 14:35:52,275 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [30972] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
2024-11-07 14:36:11,795 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:202] [31059] [MainThread] - INFO - Extracting model name from Path: /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_runs.py
2024-11-07 14:36:11,795 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:207] [31059] [MainThread] - INFO - Valid model name lavender_haze found in path /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_runs.py
2024-11-07 14:36:11,796 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:343] [31059] [MainThread] - INFO - ModelPath instance lavender_haze found in GlobalCache. Using cached instance.
2024-11-07 14:36:11,796 /Users/dylanpinheiro/Desktop/views_pipeline/model_manager.py [model_manager.py:61] [31059] [MainThread] - ERROR - Script path for config_sweep.py not found
2024-11-07 14:36:20,908 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:225] [31059] [MainThread] - INFO - SIGINT received. Deleting cache file...
2024-11-07 14:36:20,909 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [31059] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
2024-11-07 14:36:45,269 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:202] [31172] [MainThread] - INFO - Extracting model name from Path: /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_runs.py
2024-11-07 14:36:45,269 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:207] [31172] [MainThread] - INFO - Valid model name lavender_haze found in path /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_runs.py
2024-11-07 14:36:45,270 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:343] [31172] [MainThread] - INFO - ModelPath instance lavender_haze found in GlobalCache. Using cached instance.
2024-11-07 14:36:45,270 /Users/dylanpinheiro/Desktop/views_pipeline/model_manager.py [model_manager.py:61] [31172] [MainThread] - ERROR - Script path for config_sweep.py not found
2024-11-07 14:36:45,274 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:202] [31172] [MainThread] - INFO - Extracting model name from Path: /Users/dylanpinheiro/Desktop/views_pipeline/model_manager.py
2024-11-07 14:36:45,274 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:319] [31172] [MainThread] - ERROR - Error extracting model name from path: Invalid model name. Please provide a valid model name that follows the lowercase 'adjective_noun' format.
2024-11-07 14:36:49,396 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:225] [31172] [MainThread] - INFO - SIGINT received. Deleting cache file...
2024-11-07 14:36:49,398 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [31172] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
2024-11-07 14:54:01,249 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:343] [31489] [MainThread] - INFO - ModelPath instance lavender_haze found in GlobalCache. Using cached instance.
2024-11-07 14:54:01,250 /Users/dylanpinheiro/Desktop/views_pipeline/model_manager.py [model_manager.py:61] [31489] [MainThread] - ERROR - Script path for config_sweep.py not found
2024-11-07 14:54:01,253 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:202] [31489] [MainThread] - INFO - Extracting model name from Path: /Users/dylanpinheiro/Desktop/views_pipeline/model_manager.py
2024-11-07 14:54:01,253 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:319] [31489] [MainThread] - ERROR - Error extracting model name from path: Invalid model name. Please provide a valid model name that follows the lowercase 'adjective_noun' format.
2024-11-07 14:54:10,382 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:225] [31489] [MainThread] - INFO - SIGINT received. Deleting cache file...
2024-11-07 14:54:10,383 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [31489] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
2024-11-07 14:59:31,703 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:202] [31668] [MainThread] - INFO - Extracting model name from Path: /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_runs.py
2024-11-07 14:59:31,703 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:207] [31668] [MainThread] - INFO - Valid model name lavender_haze found in path /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_runs.py
2024-11-07 14:59:31,703 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:343] [31668] [MainThread] - INFO - ModelPath instance lavender_haze found in GlobalCache. Using cached instance.
2024-11-07 14:59:31,704 /Users/dylanpinheiro/Desktop/views_pipeline/model_manager.py [model_manager.py:61] [31668] [MainThread] - ERROR - Script path for config_sweep.py not found
2024-11-07 14:59:36,333 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:202] [31668] [MainThread] - INFO - Extracting model name from Path: /Users/dylanpinheiro/Desktop/views_pipeline/model_manager.py
2024-11-07 14:59:36,333 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:319] [31668] [MainThread] - ERROR - Error extracting model name from path: Invalid model name. Please provide a valid model name that follows the lowercase 'adjective_noun' format.
2024-11-07 14:59:45,243 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [31668] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
2024-11-07 15:01:40,863 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:202] [31805] [MainThread] - INFO - Extracting model name from Path: /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_runs.py
2024-11-07 15:01:40,863 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:207] [31805] [MainThread] - INFO - Valid model name lavender_haze found in path /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_runs.py
2024-11-07 15:01:40,864 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:343] [31805] [MainThread] - INFO - ModelPath instance lavender_haze found in GlobalCache. Using cached instance.
2024-11-07 15:01:40,866 /Users/dylanpinheiro/Desktop/views_pipeline/model_manager.py [model_manager.py:61] [31805] [MainThread] - ERROR - Script path for config_sweep.py not found
2024-11-07 15:01:45,531 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:202] [31805] [MainThread] - INFO - Extracting model name from Path: /Users/dylanpinheiro/Desktop/views_pipeline/model_manager.py
2024-11-07 15:01:45,531 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:319] [31805] [MainThread] - ERROR - Error extracting model name from path: Invalid model name. Please provide a valid model name that follows the lowercase 'adjective_noun' format.
2024-11-07 15:01:55,384 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [31805] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
2024-11-07 15:02:43,686 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:202] [31909] [MainThread] - INFO - Extracting model name from Path: /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_runs.py
2024-11-07 15:02:43,686 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:207] [31909] [MainThread] - INFO - Valid model name lavender_haze found in path /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_runs.py
2024-11-07 15:02:43,687 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:343] [31909] [MainThread] - INFO - ModelPath instance lavender_haze found in GlobalCache. Using cached instance.
2024-11-07 15:02:43,690 /Users/dylanpinheiro/Desktop/views_pipeline/model_manager.py [model_manager.py:61] [31909] [MainThread] - ERROR - Script path for config_sweep.py not found
2024-11-07 15:02:48,545 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:202] [31909] [MainThread] - INFO - Extracting model name from Path: /Users/dylanpinheiro/Desktop/views_pipeline/model_manager.py
2024-11-07 15:02:48,545 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:319] [31909] [MainThread] - ERROR - Error extracting model name from path: Invalid model name. Please provide a valid model name that follows the lowercase 'adjective_noun' format.
2024-11-07 15:02:59,466 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [31909] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
2024-11-07 15:03:38,038 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:202] [32023] [MainThread] - INFO - Extracting model name from Path: /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_runs.py
2024-11-07 15:03:38,038 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:207] [32023] [MainThread] - INFO - Valid model name lavender_haze found in path /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_runs.py
2024-11-07 15:03:38,039 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:343] [32023] [MainThread] - INFO - ModelPath instance lavender_haze found in GlobalCache. Using cached instance.
2024-11-07 15:03:38,042 /Users/dylanpinheiro/Desktop/views_pipeline/model_manager.py [model_manager.py:61] [32023] [MainThread] - ERROR - Script path for config_sweep.py not found
2024-11-07 15:03:42,746 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:282] [32023] [MainThread] - INFO - Fetching data from viewser...
2024-11-07 15:03:42,746 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:115] [32023] [MainThread] - INFO - Beginning file download through viewser with month range (121, 445),None
2024-11-07 15:03:42,747 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:505] [32023] [MainThread] - INFO - Queryset /Users/dylanpinheiro/Desktop/views_pipeline/common_querysets/queryset_lavender_haze.py imported successfully.
2024-11-07 15:03:42,751 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:125] [32023] [MainThread] - INFO - Found queryset for lavender_haze in common_querysets
2024-11-07 15:03:42,751 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:208] [32023] [MainThread] - INFO - Publishing queryset fatalities003_pgm_broad
2024-11-07 15:03:52,629 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [32023] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
2024-11-07 15:05:33,653 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:202] [32140] [MainThread] - INFO - Extracting model name from Path: /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_runs.py
2024-11-07 15:05:33,653 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:207] [32140] [MainThread] - INFO - Valid model name lavender_haze found in path /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_runs.py
2024-11-07 15:05:33,654 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:343] [32140] [MainThread] - INFO - ModelPath instance lavender_haze found in GlobalCache. Using cached instance.
2024-11-07 15:05:33,655 /Users/dylanpinheiro/Desktop/views_pipeline/model_manager.py [model_manager.py:61] [32140] [MainThread] - ERROR - Script path for config_sweep.py not found
2024-11-07 15:05:38,310 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:283] [32140] [MainThread] - INFO - Fetching data from viewser...
2024-11-07 15:05:38,310 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:115] [32140] [MainThread] - INFO - Beginning file download through viewser with month range 121,445
2024-11-07 15:05:38,310 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:505] [32140] [MainThread] - INFO - Queryset /Users/dylanpinheiro/Desktop/views_pipeline/common_querysets/queryset_lavender_haze.py imported successfully.
2024-11-07 15:05:38,314 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:125] [32140] [MainThread] - INFO - Found queryset for lavender_haze in common_querysets
2024-11-07 15:05:38,314 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:208] [32140] [MainThread] - INFO - Publishing queryset fatalities003_pgm_broad
2024-11-07 15:05:38,913 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:238] [32140] [MainThread] - INFO - Fetching queryset fatalities003_pgm_broad
2024-11-07 15:06:20,224 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:140] [32140] [MainThread] - WARNING - {'lavender_haze data alert 1': ' alarm: feature zero; offender: ln_ged_sb_dep, threshold: 0.95 Severity: 2 Timestamp: 2024-11-07 15:06:20\n, '}
2024-11-07 15:06:20,224 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:140] [32140] [MainThread] - WARNING - {'lavender_haze data alert 2': ' alarm: feature zero; offender: ged_sb, threshold: 0.95 Severity: 2 Timestamp: 2024-11-07 15:06:20\n, '}
2024-11-07 15:06:20,224 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:140] [32140] [MainThread] - WARNING - {'lavender_haze data alert 3': ' alarm: feature zero; offender: ged_os, threshold: 0.95 Severity: 2 Timestamp: 2024-11-07 15:06:20\n, '}
2024-11-07 15:06:20,225 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:140] [32140] [MainThread] - WARNING - {'lavender_haze data alert 4': ' alarm: feature zero; offender: ged_ns, threshold: 0.95 Severity: 2 Timestamp: 2024-11-07 15:06:20\n'}
2024-11-07 15:06:20,225 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_log_files.py [utils_log_files.py:57] [32140] [MainThread] - INFO - Data fetch log file created at /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/data/raw/calibration_data_fetch_log.txt
2024-11-07 15:06:20,225 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:291] [32140] [MainThread] - INFO - Saving data to /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/data/raw/calibration_viewser_df.pkl
2024-11-07 15:06:33,091 /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_tasks.py [execute_model_tasks.py:60] [32140] [MainThread] - INFO - Training model lavender_haze...
2024-11-07 15:06:33,092 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:343] [32140] [MainThread] - INFO - ModelPath instance lavender_haze found in GlobalCache. Using cached instance.
2024-11-07 15:06:34,060 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/stepshift/stepshift.py [stepshift.py:69] [32140] [MainThread] - WARNING - Reordering feature dimension. Save memory by setting the outcome feature as the first column in your dataframe.
2024-11-07 15:06:39,196 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:225] [32140] [MainThread] - INFO - SIGINT received. Deleting cache file...
2024-11-07 15:06:39,197 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [32140] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
2024-11-07 15:27:02,337 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:202] [32741] [MainThread] - INFO - Extracting model name from Path: /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_runs.py
2024-11-07 15:27:02,337 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:207] [32741] [MainThread] - INFO - Valid model name lavender_haze found in path /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_runs.py
2024-11-07 15:27:02,338 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:343] [32741] [MainThread] - INFO - ModelPath instance lavender_haze found in GlobalCache. Using cached instance.
2024-11-07 15:27:02,340 /Users/dylanpinheiro/Desktop/views_pipeline/model_manager.py [model_manager.py:61] [32741] [MainThread] - ERROR - Script path for config_sweep.py not found
2024-11-07 15:27:07,416 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:283] [32741] [MainThread] - INFO - Fetching data from viewser...
2024-11-07 15:27:07,416 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:115] [32741] [MainThread] - INFO - Beginning file download through viewser with month range 121,445
2024-11-07 15:27:07,416 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:505] [32741] [MainThread] - INFO - Queryset /Users/dylanpinheiro/Desktop/views_pipeline/common_querysets/queryset_lavender_haze.py imported successfully.
2024-11-07 15:27:07,421 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:125] [32741] [MainThread] - INFO - Found queryset for lavender_haze in common_querysets
2024-11-07 15:27:07,421 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:208] [32741] [MainThread] - INFO - Publishing queryset fatalities003_pgm_broad
2024-11-07 15:27:07,970 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:238] [32741] [MainThread] - INFO - Fetching queryset fatalities003_pgm_broad
2024-11-07 15:27:51,549 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:140] [32741] [MainThread] - WARNING - {'lavender_haze data alert 1': ' alarm: feature zero; offender: ln_ged_sb_dep, threshold: 0.95 Severity: 2 Timestamp: 2024-11-07 15:27:51\n, '}
2024-11-07 15:27:51,551 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:140] [32741] [MainThread] - WARNING - {'lavender_haze data alert 2': ' alarm: feature zero; offender: ged_sb, threshold: 0.95 Severity: 2 Timestamp: 2024-11-07 15:27:51\n, '}
2024-11-07 15:27:51,551 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:140] [32741] [MainThread] - WARNING - {'lavender_haze data alert 3': ' alarm: feature zero; offender: ged_os, threshold: 0.95 Severity: 2 Timestamp: 2024-11-07 15:27:51\n, '}
2024-11-07 15:27:51,551 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:140] [32741] [MainThread] - WARNING - {'lavender_haze data alert 4': ' alarm: feature zero; offender: ged_ns, threshold: 0.95 Severity: 2 Timestamp: 2024-11-07 15:27:51\n'}
2024-11-07 15:27:51,551 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_log_files.py [utils_log_files.py:57] [32741] [MainThread] - INFO - Data fetch log file created at /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/data/raw/calibration_data_fetch_log.txt
2024-11-07 15:27:51,551 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:291] [32741] [MainThread] - INFO - Saving data to /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/data/raw/calibration_viewser_df.pkl
2024-11-07 15:27:59,020 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [32741] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
2024-11-07 15:28:43,756 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:202] [32936] [MainThread] - INFO - Extracting model name from Path: /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_runs.py
2024-11-07 15:28:43,756 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:207] [32936] [MainThread] - INFO - Valid model name lavender_haze found in path /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_runs.py
2024-11-07 15:28:43,757 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:343] [32936] [MainThread] - INFO - ModelPath instance lavender_haze found in GlobalCache. Using cached instance.
2024-11-07 15:28:43,759 /Users/dylanpinheiro/Desktop/views_pipeline/model_manager.py [model_manager.py:61] [32936] [MainThread] - ERROR - Script path for config_sweep.py not found
2024-11-07 15:28:48,825 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:283] [32936] [MainThread] - INFO - Fetching data from viewser...
2024-11-07 15:28:48,825 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:115] [32936] [MainThread] - INFO - Beginning file download through viewser with month range 121,445
2024-11-07 15:28:48,826 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:505] [32936] [MainThread] - INFO - Queryset /Users/dylanpinheiro/Desktop/views_pipeline/common_querysets/queryset_lavender_haze.py imported successfully.
2024-11-07 15:28:48,830 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:125] [32936] [MainThread] - INFO - Found queryset for lavender_haze in common_querysets
2024-11-07 15:28:48,830 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:208] [32936] [MainThread] - INFO - Publishing queryset fatalities003_pgm_broad
2024-11-07 15:28:49,421 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:238] [32936] [MainThread] - INFO - Fetching queryset fatalities003_pgm_broad
2024-11-07 15:29:32,926 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:140] [32936] [MainThread] - WARNING - {'lavender_haze data alert 1': ' alarm: feature zero; offender: ln_ged_sb_dep, threshold: 0.95 Severity: 2 Timestamp: 2024-11-07 15:29:32\n, '}
2024-11-07 15:29:32,926 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:140] [32936] [MainThread] - WARNING - {'lavender_haze data alert 2': ' alarm: feature zero; offender: ged_sb, threshold: 0.95 Severity: 2 Timestamp: 2024-11-07 15:29:32\n, '}
2024-11-07 15:29:32,926 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:140] [32936] [MainThread] - WARNING - {'lavender_haze data alert 3': ' alarm: feature zero; offender: ged_os, threshold: 0.95 Severity: 2 Timestamp: 2024-11-07 15:29:32\n, '}
2024-11-07 15:29:32,926 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:140] [32936] [MainThread] - WARNING - {'lavender_haze data alert 4': ' alarm: feature zero; offender: ged_ns, threshold: 0.95 Severity: 2 Timestamp: 2024-11-07 15:29:32\n'}
2024-11-07 15:29:32,927 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_log_files.py [utils_log_files.py:57] [32936] [MainThread] - INFO - Data fetch log file created at /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/data/raw/calibration_data_fetch_log.txt
2024-11-07 15:29:32,927 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:291] [32936] [MainThread] - INFO - Saving data to /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/data/raw/calibration_viewser_df.pkl
2024-11-07 15:29:45,464 /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_tasks.py [execute_model_tasks.py:60] [32936] [MainThread] - INFO - Training model lavender_haze...
2024-11-07 15:29:45,464 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:343] [32936] [MainThread] - INFO - ModelPath instance lavender_haze found in GlobalCache. Using cached instance.
2024-11-07 15:29:46,435 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/stepshift/stepshift.py [stepshift.py:69] [32936] [MainThread] - WARNING - Reordering feature dimension. Save memory by setting the outcome feature as the first column in your dataframe.
2024-11-07 15:31:38,273 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_log_files.py [utils_log_files.py:119] [32936] [MainThread] - INFO - Log file created at /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/data/generated/calibration_log.txt
2024-11-07 15:31:38,288 /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_tasks.py [execute_model_tasks.py:74] [32936] [MainThread] - INFO - Done. Runtime: 1.980 minutes.

2024-11-07 15:31:49,987 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [32936] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
2024-11-07 15:54:39,865 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:202] [33884] [MainThread] - INFO - Extracting model name from Path: /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_runs.py
2024-11-07 15:54:39,865 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:207] [33884] [MainThread] - INFO - Valid model name lavender_haze found in path /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_runs.py
2024-11-07 15:54:39,865 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:343] [33884] [MainThread] - INFO - ModelPath instance lavender_haze found in GlobalCache. Using cached instance.
2024-11-07 15:54:39,866 /Users/dylanpinheiro/Desktop/views_pipeline/model_manager.py [model_manager.py:61] [33884] [MainThread] - ERROR - Script path for config_sweep.py not found
2024-11-07 15:54:44,963 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:283] [33884] [MainThread] - INFO - Fetching data from viewser...
2024-11-07 15:54:44,963 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:115] [33884] [MainThread] - INFO - Beginning file download through viewser with month range 121,445
2024-11-07 15:54:44,964 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:505] [33884] [MainThread] - INFO - Queryset /Users/dylanpinheiro/Desktop/views_pipeline/common_querysets/queryset_lavender_haze.py imported successfully.
2024-11-07 15:54:44,969 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:125] [33884] [MainThread] - INFO - Found queryset for lavender_haze in common_querysets
2024-11-07 15:54:44,969 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:208] [33884] [MainThread] - INFO - Publishing queryset fatalities003_pgm_broad
2024-11-07 15:54:45,615 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:238] [33884] [MainThread] - INFO - Fetching queryset fatalities003_pgm_broad
2024-11-07 15:55:27,452 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:140] [33884] [MainThread] - WARNING - {'lavender_haze data alert 1': ' alarm: feature zero; offender: ln_ged_sb_dep, threshold: 0.95 Severity: 2 Timestamp: 2024-11-07 15:55:27\n, '}
2024-11-07 15:55:27,452 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:140] [33884] [MainThread] - WARNING - {'lavender_haze data alert 2': ' alarm: feature zero; offender: ged_sb, threshold: 0.95 Severity: 2 Timestamp: 2024-11-07 15:55:27\n, '}
2024-11-07 15:55:27,452 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:140] [33884] [MainThread] - WARNING - {'lavender_haze data alert 3': ' alarm: feature zero; offender: ged_os, threshold: 0.95 Severity: 2 Timestamp: 2024-11-07 15:55:27\n, '}
2024-11-07 15:55:27,452 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:140] [33884] [MainThread] - WARNING - {'lavender_haze data alert 4': ' alarm: feature zero; offender: ged_ns, threshold: 0.95 Severity: 2 Timestamp: 2024-11-07 15:55:27\n'}
2024-11-07 15:55:27,452 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_log_files.py [utils_log_files.py:57] [33884] [MainThread] - INFO - Data fetch log file created at /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/data/raw/calibration_data_fetch_log.txt
2024-11-07 15:55:27,453 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:291] [33884] [MainThread] - INFO - Saving data to /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/data/raw/calibration_viewser_df.pkl
2024-11-07 15:55:34,552 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [33884] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
2024-11-07 15:59:46,730 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:202] [34161] [MainThread] - INFO - Extracting model name from Path: /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_runs.py
2024-11-07 15:59:46,730 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:207] [34161] [MainThread] - INFO - Valid model name lavender_haze found in path /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_runs.py
2024-11-07 15:59:46,730 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:343] [34161] [MainThread] - INFO - ModelPath instance lavender_haze found in GlobalCache. Using cached instance.
2024-11-07 15:59:46,731 /Users/dylanpinheiro/Desktop/views_pipeline/model_manager.py [model_manager.py:61] [34161] [MainThread] - ERROR - Script path for config_sweep.py not found
2024-11-07 15:59:51,802 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:283] [34161] [MainThread] - INFO - Fetching data from viewser...
2024-11-07 15:59:51,802 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:115] [34161] [MainThread] - INFO - Beginning file download through viewser with month range 121,445
2024-11-07 15:59:51,802 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:505] [34161] [MainThread] - INFO - Queryset /Users/dylanpinheiro/Desktop/views_pipeline/common_querysets/queryset_lavender_haze.py imported successfully.
2024-11-07 15:59:51,808 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:125] [34161] [MainThread] - INFO - Found queryset for lavender_haze in common_querysets
2024-11-07 15:59:51,808 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:208] [34161] [MainThread] - INFO - Publishing queryset fatalities003_pgm_broad
2024-11-07 15:59:52,454 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:238] [34161] [MainThread] - INFO - Fetching queryset fatalities003_pgm_broad
2024-11-07 15:59:56,098 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:225] [34161] [MainThread] - INFO - SIGINT received. Deleting cache file...
2024-11-07 15:59:56,099 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [34161] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
2024-11-07 16:00:04,632 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:202] [34270] [MainThread] - INFO - Extracting model name from Path: /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_runs.py
2024-11-07 16:00:04,632 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:207] [34270] [MainThread] - INFO - Valid model name lavender_haze found in path /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/src/management/execute_model_runs.py
2024-11-07 16:00:04,633 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:343] [34270] [MainThread] - INFO - ModelPath instance lavender_haze found in GlobalCache. Using cached instance.
2024-11-07 16:00:04,635 /Users/dylanpinheiro/Desktop/views_pipeline/model_manager.py [model_manager.py:61] [34270] [MainThread] - ERROR - Script path for config_sweep.py not found
2024-11-07 16:00:09,679 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:283] [34270] [MainThread] - INFO - Fetching data from viewser...
2024-11-07 16:00:09,679 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:115] [34270] [MainThread] - INFO - Beginning file download through viewser with month range 121,445
2024-11-07 16:00:09,680 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:505] [34270] [MainThread] - INFO - Queryset /Users/dylanpinheiro/Desktop/views_pipeline/common_querysets/queryset_lavender_haze.py imported successfully.
2024-11-07 16:00:09,686 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:125] [34270] [MainThread] - INFO - Found queryset for lavender_haze in common_querysets
2024-11-07 16:00:09,686 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:208] [34270] [MainThread] - INFO - Publishing queryset fatalities003_pgm_broad
2024-11-07 16:00:11,697 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:238] [34270] [MainThread] - INFO - Fetching queryset fatalities003_pgm_broad
2024-11-07 16:00:52,992 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:140] [34270] [MainThread] - WARNING - {'lavender_haze data alert 1': ' alarm: feature zero; offender: ln_ged_sb_dep, threshold: 0.95 Severity: 2 Timestamp: 2024-11-07 16:00:52\n, '}
2024-11-07 16:00:52,992 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:140] [34270] [MainThread] - WARNING - {'lavender_haze data alert 2': ' alarm: feature zero; offender: ged_sb, threshold: 0.95 Severity: 2 Timestamp: 2024-11-07 16:00:52\n, '}
2024-11-07 16:00:52,992 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:140] [34270] [MainThread] - WARNING - {'lavender_haze data alert 3': ' alarm: feature zero; offender: ged_os, threshold: 0.95 Severity: 2 Timestamp: 2024-11-07 16:00:52\n, '}
2024-11-07 16:00:52,992 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:140] [34270] [MainThread] - WARNING - {'lavender_haze data alert 4': ' alarm: feature zero; offender: ged_ns, threshold: 0.95 Severity: 2 Timestamp: 2024-11-07 16:00:52\n'}
2024-11-07 16:00:52,992 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_log_files.py [utils_log_files.py:57] [34270] [MainThread] - INFO - Data fetch log file created at /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/data/raw/calibration_data_fetch_log.txt
2024-11-07 16:00:52,993 /Users/dylanpinheiro/Desktop/views_pipeline/dataloaders.py [dataloaders.py:291] [34270] [MainThread] - INFO - Saving data to /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/data/raw/calibration_viewser_df.pkl
2024-11-07 16:01:05,494 /Users/dylanpinheiro/Desktop/views_pipeline/model_manager.py [model_manager.py:170] [34270] [MainThread] - INFO - Training model lavender_haze...
2024-11-07 16:01:05,494 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:343] [34270] [MainThread] - INFO - ModelPath instance lavender_haze found in GlobalCache. Using cached instance.
2024-11-07 16:01:06,493 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/stepshift/stepshift.py [stepshift.py:69] [34270] [MainThread] - WARNING - Reordering feature dimension. Save memory by setting the outcome feature as the first column in your dataframe.
2024-11-07 16:03:05,845 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_log_files.py [utils_log_files.py:119] [34270] [MainThread] - INFO - Log file created at /Users/dylanpinheiro/Desktop/views_pipeline/models/lavender_haze/data/generated/calibration_log.txt
2024-11-07 16:03:05,864 /Users/dylanpinheiro/Desktop/views_pipeline/model_manager.py [model_manager.py:184] [34270] [MainThread] - INFO - Done. Runtime: 2.099 minutes.

2024-11-07 16:03:12,927 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [34270] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
